{
    "title" : "RabbitMQ: None of the specified endpoints were reachable",
    "uri" : "http://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
    "printableUri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
    "clickUri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
    "excerpt" : "RabbitMQ: None of the specified endpoints were reachable ... I get the None of the specified endpoints were reachable message in Diagnostic logs. ... I checked and found RabbitMQ for Sitecore servi...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1108,
    "percentScore" : 74.90078,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "RabbitMQ: None of the specified endpoints were reachable",
      "sysauthor" : "erkany",
      "sysurihash" : "Y7q7n5ðOr8ATpIBN",
      "urihash" : "Y7q7n5ðOr8ATpIBN",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160353,
      "questionaskeddatestring" : "·\n            Jul 14, 2015 at 02:33 PM ·",
      "tags" : [ "coveoforsitecore", "rabbitmq" ],
      "sysconcepts" : "specified endpoints ; RabbitMQ ; logs ; guest ; QueueURI settings ; admin ; username ; credentials ; localhost",
      "concepts" : "specified endpoints ; RabbitMQ ; logs ; guest ; QueueURI settings ; admin ; username ; credentials ; localhost",
      "printableuri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942202000,
      "permanentid" : "b38fbc0a92cd5049be373c02a68e81b0b4f1281bb2bd41813020433f9355",
      "syslanguage" : [ "English" ],
      "transactionid" : 160353,
      "title" : "RabbitMQ: None of the specified endpoints were reachable",
      "date" : 1436832000000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Jean-François L'Heureux" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "Jean-François L'Heureux \u2666\u2666", "erkany", "erkany" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5447674,
      "numberofcomments" : 3,
      "size" : 75714,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911577974,
      "acceptedanswers" : 1,
      "syssize" : 75714,
      "sysdate" : 1436832000000,
      "author" : "erkany",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>Hi,</p> \n<p>I get the None of the specified endpoints were reachable message in Diagnostic logs. </p> \n<p>I checked and found RabbitMQ for Sitecore service is running but I can't access <a rel=\"nofollow\" href=\"http://localhost:15672\">http://localhost:15672</a> to verify the QueueURI settings.</p> \n<p>Please help</p>\n                </div>",
      "sitemaplastmodified" : 1436832000000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942202000,
      "questionnumber" : 5470,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "erkany",
      "sitename" : "Answers",
      "sysrowid" : 5447674,
      "uri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "RabbitMQ: None of the specified endpoints were reachable",
    "Uri" : "http://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
    "PrintableUri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
    "ClickUri" : "https://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/5470/rabbitmq-none-of-the-specified-endpoints-were-reac.html",
    "Excerpt" : "RabbitMQ: None of the specified endpoints were reachable ... I get the None of the specified endpoints were reachable message in Diagnostic logs. ... I checked and found RabbitMQ for Sitecore servi...",
    "FirstSentences" : null
  }