{
    "title" : "Sitecore Content Delivery, referencing Content Management index causing exception",
    "uri" : "http://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
    "printableUri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
    "clickUri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
    "excerpt" : "Indexes are being managed and queried successfully, across both CM & CD farms. ... Issue: ... We are seeing repeated exceptions in the Sitecore logs on CD instances that suggest a process is attemp...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1030,
    "percentScore" : 72.21627,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Sitecore Content Delivery, referencing Content Management index causing exception",
      "sysauthor" : "jimschram",
      "sysurihash" : "ñmLEYGDV8qrCñuae",
      "urihash" : "ñmLEYGDV8qrCñuae",
      "numberofanswers" : 2,
      "sysuri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160351,
      "questionaskeddatestring" : "·\n            Apr 30, 2015 at 02:20 PM ·",
      "tags" : [ "coveoforsitecore", "sitecore", "azure" ],
      "sysconcepts" : "indexing ; Sitecore ; remote events ; Core database ; exceptions ; potential patch ; handler set ; queried successfully ; ArgumentException ; configuration ; environment",
      "concepts" : "indexing ; Sitecore ; remote events ; Core database ; exceptions ; potential patch ; handler set ; queried successfully ; ArgumentException ; configuration ; environment",
      "printableuri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942109000,
      "permanentid" : "c7b48a955e16952cad96a8cd7a7ab5713e3887115c5bc70d89ed344ff6fd",
      "syslanguage" : [ "English" ],
      "transactionid" : 160351,
      "title" : "Sitecore Content Delivery, referencing Content Management index causing exception",
      "date" : 1430784000000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "jimschram", "Luc Bergeron" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "jimschram" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5447561,
      "numberofcomments" : 1,
      "size" : 80925,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911577860,
      "acceptedanswers" : 1,
      "syssize" : 80925,
      "sysdate" : 1430784000000,
      "author" : "jimschram",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>Background:</p> \n<ul> \n <li><p> Sitecore 7.5, using Sitecore Azure Module, our own MongoDB, Coveo environment in Azure </p> </li> \n <li><p> Multiple instance Content Management (CM) farm - Azure PaaS Cloud Service Web Roles </p> </li> \n <li><p> Multiple instance Content Delivery (CD) farm - Azure PaaS Cloud Service Web Roles </p> </li> \n <li><p> Community Edition Coveo installed - Azure IaaS VMs: 1 Master, 1 Mirror </p> </li> \n <li><p> CM Databases: Core, Master, Web, Reporting + MongoDB databases/collections for xDB </p> </li> \n <li><p> CD Databases: Core (shared with CM), Web (Not shared w/ CM) </p> </li> \n <li><p> CM Indexes: Coveo-CM-core-index, Coveo-CM-master-index, Coveo-CM-web-index, Coveo-CD-web-index </p> </li> \n <li><p> CD Indexes: Coveo_CD-web-index w/ section removed from index config (maintained via CM) </p> </li> \n</ul> \n<p>Indexes are being managed and queried successfully, across both CM & CD farms.</p> \n<p>Issue: </p> \n<p>We are seeing repeated exceptions in the Sitecore logs on CD instances that suggest a process is attempting reference an index for the CM environment. No instances of the CM index name found in the CD configs.</p> \n<p>Exception:</p> \n<pre><code> Heartbeat 2015:04:30 13:14:07 ERROR Exception while handling event Sitecore.ContentSearch.Events.IndexingFinishedEvent\n Exception: System.ArgumentException\n Message: Index Coveo_CM_master_index was not found\n Source: Sitecore.ContentSearch\n    at Sitecore.ContentSearch.Events.IndexingEventHandler.UpdateIndexTimestampDirectHandler(Object sender, EventArgs args)\n    at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result)\n    at Sitecore.Events.Event.RaiseEvent(String eventName, Object[] parameters)\n    at Sitecore.ContentSearch.Maintenance.EventHub.<>c__DisplayClass16.<Initialize>b__b(IndexingFinishedEvent event)\n    at Sitecore.Eventing.EventProvider.RaiseEvent(Object event, Type eventType, EventContext context)\n\n</code></pre> \n<p>The only thing that I can come up with so far is that CM & CD are sharing the same Core database and there may be something miss-configured in CD that is attempting to run a task or pipeline based on something in the shared Core database.</p> \n<p>Any ideas what configuration(s) may be causing this exception and what the resolution might be?</p>\n                </div>",
      "sitemaplastmodified" : 1430784000000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942109000,
      "questionnumber" : 4793,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "jimschram",
      "sitename" : "Answers",
      "sysrowid" : 5447561,
      "uri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Sitecore Content Delivery, referencing Content Management index causing exception",
    "Uri" : "http://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
    "PrintableUri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
    "ClickUri" : "https://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/4793/sitecore-content-delivery-referencing-content-mana.html",
    "Excerpt" : "Indexes are being managed and queried successfully, across both CM & CD farms. ... Issue: ... We are seeing repeated exceptions in the Sitecore logs on CD instances that suggest a process is attemp...",
    "FirstSentences" : null
  }