{
    "title" : "Unable to access Sitecore or restart security provider",
    "uri" : "http://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
    "printableUri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
    "clickUri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
    "excerpt" : "I have been using Coveo successfully for a time on a local Sitecore site, and then one day (for no reason as far as I can tell) my Coveo stopped working and I noticed the security provider was mark...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1030,
    "percentScore" : 72.21627,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Unable to access Sitecore or restart security provider",
      "sysauthor" : "kenneths",
      "sysurihash" : "N02PnksV2gyTuc1h",
      "urihash" : "N02PnksV2gyTuc1h",
      "numberofanswers" : 2,
      "sysuri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160347,
      "questionaskeddatestring" : "·\n            Aug 06, 2014 at 11:54 AM ·",
      "tags" : [ "coveoforsitecore", "sitecore", "security" ],
      "sysconcepts" : "security provider ; coveo ; web services ; re-entered the password ; calls ; credentials ; Admin account ; Vincent ; troubleshoot ; GetDomainNames",
      "concepts" : "security provider ; coveo ; web services ; re-entered the password ; calls ; credentials ; Admin account ; Vincent ; troubleshoot ; GetDomainNames",
      "printableuri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517941824000,
      "permanentid" : "e6091e7966a7c3ca8cca2fd86248c5fa19a7b69147273f201dbddfd05c74",
      "syslanguage" : [ "English" ],
      "transactionid" : 160347,
      "title" : "Unable to access Sitecore or restart security provider",
      "date" : 1407369600000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Vincent Séguin", "kenneths" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5447032,
      "numberofcomments" : 0,
      "size" : 81266,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911577476,
      "acceptedanswers" : 1,
      "syssize" : 81266,
      "sysdate" : 1407369600000,
      "author" : "kenneths",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>Hello,</p> \n<p>I have been using Coveo successfully for a time on a local Sitecore site, and then one day (for no reason as far as I can tell) my Coveo stopped working and I noticed the security provider was marked as invalid. I tried to restart it, but got this message: \"Unable to restart the Sitecore Security Provider for VSLT-6RZY8Z1-Commonwealth security provider: Refer to the system logs for more details.\"</p> \n<p>The log has these errors:</p> \n<p>ERROR 11:39:28 AM An error occurred while initializing the Blade \"<em>MySecurityProviderName</em>\" (ID #49): Unexpected exception in method 'InitBlade': System.InvalidOperationException: Client found response content type of 'text/html; charset=utf-8', but expected 'text/xml'.The request failed with an empty response. ---> System.InvalidOperationException: Client found response content type of 'text/html; charset=utf-8', but expected 'text/xml'.The request failed with an empty response. at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall) at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters) at Coveo.CNL.WebServices.WebServiceUtilities.InvokeWithCallBack(InvokeMethodDelegate p_InvokeMethod, SoapCallBack p_SoapCallBack, String p_MethodName, Object[] p_Parameters) at Coveo.Connectors.Sitecore2.SitecoreWS.SitecoreWebService.GetSiteDatabase(String p_TargetSite) at Coveo.Connectors.Sitecore2.Connection.Sitecore2Connection.GetSiteDatabaseName() at Coveo.Connectors.Sitecore2.Configuration.Sitecore2ConnectorConfiguration.InitializeDatabase(GetDefaultValueDelegate p_GetDatabaseNameDelegate) at Coveo.Connectors.Sitecore2.Connection.Sitecore2Connection.Initialize() at Coveo.CES.CustomCrawlers.Sitecore2.Security.Sitecore2SecurityProvider.InitSecurityProvider() at Coveo.CES.SecurityProviders.Framework.SecurityProviderBase.<>c_<em>DisplayClass1a.b</em>_19() --- End of inner exception stack trace --- at Coveo.CES.SecurityProviders.Framework.SecurityProviderBase.ExecuteMonitoredCall(MonitoredCall p_MonitoredCall) at Coveo.CES.SecurityProviders.Framework.SecurityProviderBase.InitBlade(BladeDefinitionConfig p_BladeConfig)</p> \n<p>ERROR 11:39:28 AM NodeId #47: An error occurred while initializing the Blade \"<em>MySecurityProviderName</em>\" (ID #49): Unexpected exception in method 'InitBlade': System.InvalidOperationException: Client found response content type of 'text/html; charset=utf-8', but expected 'text/xml'.The request failed with an empty response. ---> System.InvalidOperationException: Client found response content type of 'text/html; charset=utf-8', but expected 'text/xml'.The request failed with an empty response. at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall) at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters) at Coveo.CNL.WebServices.WebServiceUtilities.InvokeWithCallBack(InvokeMethodDelegate p_InvokeMethod, SoapCallBack p_SoapCallBack, String p_MethodName, Object[] p_Parameters) at Coveo.Connectors.Sitecore2.SitecoreWS.SitecoreWebService.GetSiteDatabase(String p_TargetSite) at Coveo.Connectors.Sitecore2.Connection.Sitecore2Connection.GetSiteDatabaseName() at Coveo.Connectors.Sitecore2.Configuration.Sitecore2ConnectorConfiguration.InitializeDatabase(GetDefaultValueDelegate p_GetDatabaseNameDelegate) at Coveo.Connectors.Sitecore2.Connection.Sitecore2Connection.Initialize() at Coveo.CES.CustomCrawlers.Sitecore2.Security.Sitecore2SecurityProvider.InitSecurityProvider() at Coveo.CES.SecurityProviders.Framework.SecurityProviderBase.<>c_<em>DisplayClass1a.b</em>_19() --- End of inner exception stack trace --- at Coveo.CES.SecurityProviders.Framework.SecurityProviderBase.ExecuteMonitoredCall(MonitoredCall p_MonitoredCall) at Coveo.CES.SecurityProviders.Framework.SecurityProviderBase.InitBlade(BladeDefinitionConfig p_BladeConfig)</p> \n<p>I have had this in the past. Then I simple re-entered the password for the security provider and everything was working fine again. This time, however, I have re-entered the password several different times and it still doesn't work. I have tried switching the security provider to use the Sitecore\\Admin account and that still doesn't work. I know the username/passwords are correct because I can log directly into Sitecore with them.</p> \n<p>I have also restarted the coveo service and that didn't change a thing.</p> \n<p>Any help would be greatly appreciated. </p>\n                </div>",
      "sitemaplastmodified" : 1407369600000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517941824000,
      "questionnumber" : 2207,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "kenneths",
      "sitename" : "Answers",
      "sysrowid" : 5447032,
      "uri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Unable to access Sitecore or restart security provider",
    "Uri" : "http://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
    "PrintableUri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
    "ClickUri" : "https://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/2207/unable-to-access-sitecore-or-restart-security-prov.html",
    "Excerpt" : "I have been using Coveo successfully for a time on a local Sitecore site, and then one day (for no reason as far as I can tell) my Coveo stopped working and I noticed the security provider was mark...",
    "FirstSentences" : null
  }