{
    "title" : "External field not present in raw data",
    "uri" : "http://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
    "printableUri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
    "clickUri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
    "excerpt" : "I have an external source configured in coveo for sitecore. ... After a recent upgrade to 4.0, I'm unable to get my external field showing in the raw data returned from the search API. ... This fie...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1165,
    "percentScore" : 76.803215,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "External field not present in raw data",
      "sysauthor" : "benaldo",
      "sysurihash" : "vAjpdkXIQtDWJMsH",
      "urihash" : "vAjpdkXIQtDWJMsH",
      "numberofanswers" : 0,
      "sysuri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160363,
      "questionaskeddatestring" : "·\n            Dec 15, 2016 at 09:52 AM ·",
      "tags" : [ "coveoforsitecore", "searchapi", "external", "fields" ],
      "sysconcepts" : "external field ; raw ; sitecore ; fieldMap ; coveo ; AddFieldByFieldName ; config file ; Provider Custom ; AddExternalField ; patch location ; multi-value facet ; configuration",
      "concepts" : "external field ; raw ; sitecore ; fieldMap ; coveo ; AddFieldByFieldName ; config file ; Provider Custom ; AddExternalField ; patch location ; multi-value facet ; configuration",
      "printableuri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942921000,
      "permanentid" : "5b3fb11056c200750fb4592c1a7624fa1859e13a5e58a7256d02f04fca7d",
      "syslanguage" : [ "English" ],
      "transactionid" : 160363,
      "title" : "External field not present in raw data",
      "date" : 1483315200000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "hasanswer" : "false",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "Simon \u2666\u2666", "benaldo", "Jean-François L'Heureux \u2666\u2666" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5448656,
      "numberofcomments" : 3,
      "size" : 71085,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911578934,
      "acceptedanswers" : 0,
      "syssize" : 71085,
      "sysdate" : 1483315200000,
      "author" : "benaldo",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>Hi,</p> \n<p>I have an external source configured in coveo for sitecore. After a recent upgrade to 4.0, I'm unable to get my external field showing in the raw data returned from the search API. This field is also present for the sitecore items, if that makes a difference. Here's what I've tried so far:</p> \n<ul> \n <li><p> Added the field to the raw:AddFieldByFieldName section under fieldMap </p> </li> \n <li><p> Added the field to the raw:AddExternalField section under fieldMap </p> </li> \n <li><p> Tried it in both spots just to try </p> </li> \n <li><p> Confirmed that the field is present for items that I'm testing on using the Index Browser </p> </li> \n <li><p> Confirmed the field is enabled for Field Queries in CES admin (it has field queries, multi-value facet, and display field checked)</p> <h2>Is there something simple I'm missing here? Or any other places I should look? Thanks!</h2> </li> \n</ul> \n<p>I have the external fields patching in from a separate file (app_config\\include\\coveo\\z_coveo.external.fields.config). I've confirmed in the showConfig that they are going to the right place.</p> \n<pre><code> <configuration xmlns:patch=\"http://www.sitecore.net/xmlconfig/\">\n   <sitecore>\n       <coveo>\n         <defaultIndexConfiguration>\n           <fieldMap type=\"Coveo.SearchProvider.CoveoFieldMap, Coveo.SearchProvider\">\n             <externalFields hint=\"raw:AddExternalField\">\n                <field fieldName=\"categoryhierarchy\" fieldTypeName=\"string\" />\n              </externalFields>\n         </defaultIndexConfiguration>\n       </coveo>\n   </sitecore>\n </configuration>\n</code></pre>\n                </div>",
      "sitemaplastmodified" : 1483315200000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942921000,
      "questionnumber" : 9908,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "benaldo",
      "sitename" : "Answers",
      "sysrowid" : 5448656,
      "uri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "External field not present in raw data",
    "Uri" : "http://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
    "PrintableUri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
    "ClickUri" : "https://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/9908/external-field-not-present-in-raw-data.html",
    "Excerpt" : "I have an external source configured in coveo for sitecore. ... After a recent upgrade to 4.0, I'm unable to get my external field showing in the raw data returned from the search API. ... This fie...",
    "FirstSentences" : null
  }