{
    "title" : "The remote server returned an error: (404) Not Found.",
    "uri" : "http://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
    "printableUri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
    "clickUri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
    "excerpt" : "May be the url need to return a Json? ... </restEndpointConfiguration> </coveo> </sitecore> </configuration> ... When I try to rebuild the index no error is promted inside the log files but it rema...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1157,
    "percentScore" : 76.53906,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "The remote server returned an error: (404) Not Found.",
      "sysauthor" : "danteciambella",
      "sysurihash" : "Z8ifij14hE6RJ4o1",
      "urihash" : "Z8ifij14hE6RJ4o1",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160361,
      "questionaskeddatestring" : "·\n            Nov 16, 2016 at 06:40 AM ·",
      "tags" : [ "endpoint", "end", "404" ],
      "sysconcepts" : "coveo ; server ; endpoint ; configuration ; sitecore ; Search API ; endless state ; localhost ; searchApiUri ; troubleshoot ; YourSitecoreInstanceHostName ; ShowConfig ; restEndpointConfiguration",
      "concepts" : "coveo ; server ; endpoint ; configuration ; sitecore ; Search API ; endless state ; localhost ; searchApiUri ; troubleshoot ; YourSitecoreInstanceHostName ; ShowConfig ; restEndpointConfiguration",
      "printableuri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942846000,
      "permanentid" : "a67f6d9e414c4561dd8b09b99fa80d350270127bad2ea988b857f8bc7ac6",
      "syslanguage" : [ "English" ],
      "transactionid" : 160361,
      "title" : "The remote server returned an error: (404) Not Found.",
      "date" : 1479427200000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Jean-François L'Heureux" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "François Lachance-Guillemette \u2666\u2666", "danteciambella", "François Lachance-Guillemette \u2666\u2666", "Jean-François L'Heureux \u2666\u2666", "danteciambella", "Jean-François L'Heureux \u2666\u2666", "danteciambella" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5448547,
      "numberofcomments" : 7,
      "size" : 94937,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911578846,
      "acceptedanswers" : 1,
      "syssize" : 94937,
      "sysdate" : 1479427200000,
      "author" : "danteciambella",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>I have the following error tring to call rthe url: <code>http://xxxxxxxxxxxxxxx/sitecore%20modules/Web/Coveo/Admin/CoveoDiagnosticPage.aspx The remote server returned an error: (404) Not Found.</code> (in red)</p> \n<p>I have done the following checks:</p> \n<p><a rel=\"nofollow\" href=\"https://localhost:52810/7.0/CoveoSearchService?wsdl\">https://localhost:52810/7.0/CoveoSearchService?wsdl</a> is working (attention is configured in https) <a rel=\"nofollow\" href=\"http://localhost:8080/rest/search?q=test\">http://localhost:8080/rest/search?q=test</a> coveo search API is working --> return a Json <a rel=\"nofollow\" href=\"http://localhost:8080/coveo/rest\">http://localhost:8080/coveo/rest</a> it return the following:</p> \n<p>Requesting \"GET /coveo/rest\" on servlet \"\" but only have:</p> \n<pre><code> â\x80¢DELETE /:page\n â\x80¢GET /\n â\x80¢GET /*/lib/69F7FB52CFF1A92A6C5A6B2DE9719937/interface-editor/*\n â\x80¢GET /*/lib/69F7FB52CFF1A92A6C5A6B2DE9719937/jsui/*\n â\x80¢GET /*/lib/interface-editor/*\n â\x80¢GET /*/lib/jsui/*\n â\x80¢GET /:page\n â\x80¢GET /:page/edit\n â\x80¢GET /:page/load\n â\x80¢GET /:page/zip\n â\x80¢GET /favicon.ico\n â\x80¢GET /lib/*\n â\x80¢GET /lib/69F7FB52CFF1A92A6C5A6B2DE9719937/interface-editor/*\n â\x80¢GET /lib/69F7FB52CFF1A92A6C5A6B2DE9719937/jsui/*\n â\x80¢GET /lib/interface-editor/*\n â\x80¢GET /lib/jsui/*\n â\x80¢GET /util/isSearchPageDesigner\n â\x80¢GET /util/repositories\n â\x80¢POST /:page/save\n â\x80¢PUT /:page\n\n</code></pre> \n<p>is it correct? May be the url need to return a Json? The following is the Coveo.SearchProvider.Rest.config file content:</p> \n<pre><code> <configuration xmlns:patch=\"http://www.sitecore.net/xmlconfig/\">\n   <sitecore>\n     <pipelines>\n       <!-- Pipeline used to customize the JSON response of the search REST endpoint. -->\n       <coveoProcessRestJsonResponse>\n         <processor type=\"Coveo.SearchProvider.Rest.Processors.CoveoProcessRestJsonResponse.ParseJsonRestSearchResponseProcessor, Coveo.SearchProvider.Rest\" />\n       </coveoProcessRestJsonResponse>\n       <!-- Pipeline used to customize the information returned by the REST endpoint. -->\n       <coveoProcessParsedRestResponse>\n         <!-- This processor resolves the REST results clickUri field in the context of the current site using the Sitecore LinkManager. -->\n         <processor type=\"Coveo.SearchProvider.Rest.Processors.CoveoProcessParsedRestResponse.ResolveResultClickableUriProcessor, Coveo.SearchProvider.Rest\" />\n       </coveoProcessParsedRestResponse>\n       <getSearchUserIdentities>\n         <!-- This processor adds the virtual groups to the search identities when the active user is a virtual user. -->\n         <processor type=\"Coveo.SearchProvider.Rest.Processors.GetSearchUserIdentities.AddVirtualGroups, Coveo.SearchProvider.Rest\" />\n         <!-- This processor adds the expanded user mappings to the search identities. -->\n         <!--\n         <processor type=\"Coveo.SearchProvider.Rest.Processors.GetSearchUserIdentities.AddUserMappings, Coveo.SearchProvider.Rest\" />\n         -->\n         <!-- This processor maps Sitecore users to Active Directory users by following a domain mapping. -->\n         <!--\n         <processor type=\"Coveo.SearchProvider.Rest.Processors.GetSearchUserIdentities.AddActiveDirectoryIdentity, Coveo.SearchProvider.Rest\">\n           <domainMappings hint=\"raw:AddDomainMapping\">\n             <domainMapping sitecoreDomain=\"ad\" adDomain=\"acme.corp.com\" />\n           </domainMappings>\n         </processor>\n         -->\n       </getSearchUserIdentities>\n       <getUserMappings>\n         <!-- This processor uses the e-mail address from the user profile to expand to an e-mail user identity. -->\n         <processor type=\"Coveo.SearchProvider.Rest.Processors.GetUserMappings.AddSitecoreUserEmailIdentity, Coveo.SearchProvider.Rest\" />\n       </getUserMappings>\n       <!-- The \"getUserMembers\" is exposed by Sitecore2's web service. Therefore, the \"getUserMappings\" pipeline\n            should be used instead to control to which identities a Sitecore user identity is expanded. -->\n       <getUserMembers>\n         <!-- This processor invokes the \"getUserMappings\" pipeline in order to expand a Sitecore user identity.\n              Invoking the \"getUserMappings\" pipeline from here ensures a consistent user expansion between on-premises and Cloud deployments. -->\n         <processor type=\"Coveo.SearchProvider.Rest.Processors.Sitecore2.GetUserMembers.InvokeGetUserMappingsPipeline, Coveo.SearchProvider.Rest\" />\n       </getUserMembers>\n       <httpRequestBegin>\n         <!-- This processor is required to ensure that requests targeting the REST endpoint are not handled by Sitecore. -->\n         <processor patch:before=\"processor[@type = 'Sitecore.Pipelines.HttpRequest.ItemResolver, Sitecore.Kernel']\" type=\"Coveo.SearchProvider.Rest.Processors.HttpRequestBegin.TransferCoveoRestSearchRequest, Coveo.SearchProvider.Rest\" />\n       </httpRequestBegin>\n       <httpRetry.SearchExceptionsHandler>\n         <processor name=\"CoveoWaitAndRetryCleanUpCall\" type=\"Coveo.Framework.Utils.Rest.HttpWaitAndRetry, Coveo.Framework\">\n           <retryGroups hint=\"list:AddGroup\">\n             <retryGroup name=\"SecurityProviderNotRegistered\" type=\"Coveo.Framework.Utils.Rest.HttpWaitAndRetryGroup, Coveo.Framework\">\n               <retryStrategy type=\"Coveo.Framework.Utils.Rest.ConstantIntervalRetryStrategy\">\n                 <numberOfRetry>20</numberOfRetry>\n                 <interval>00:00:30</interval>\n               </retryStrategy>\n               <conditions hint=\"raw:AddCondition\">\n                 <condition statusCodes=\"400\" responseMatch=\"SecurityProviderNotRegistered\" />\n               </conditions>\n             </retryGroup>\n             <group name=\"ThrottlingAndTimeout\" ref=\"coveo/retryGroups/throttlingAndTimeout\" />\n           </retryGroups>\n         </processor>\n       </httpRetry.SearchExceptionsHandler>\n     </pipelines>\n     <coveo>\n       <!-- Coveo Rest endpoint search settings -->\n       <restEndpointConfiguration type=\"Coveo.Framework.Configuration.RestEndpointConfiguration, Coveo.Framework\">\n         <!-- The secret key must be configured in the search api service as well. This way, the search api service can trust the application. -->\n         <applicationSecret>removed but filled correctly</applicationSecret>\n         <!-- The timeout period for requests going through the search api proxy.-->\n         <requestTimeout>00:00:30</requestTimeout>\n         <!-- Defines the location of the REST endpoint in the website. -->\n         <restEndpointPath>/coveo/rest</restEndpointPath>\n         <!-- The period during which the search token is valid. -->\n         <searchTokenExpiration>01:00:00</searchTokenExpiration>\n         <!-- The URI to connect to the search api service. -->\n         <searchApiUri>http://localhost:8080/</searchApiUri>\n       </restEndpointConfiguration>\n     </coveo>\n   </sitecore>\n </configuration>\n\n</code></pre> \n<p>When I try to rebuild the index no error is promted inside the log files but it remain in a endless state and I need to close the rebuild in dex pop up. Thanks in advance.</p>\n                </div>",
      "sitemaplastmodified" : 1479427200000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942846000,
      "questionnumber" : 9620,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "danteciambella",
      "sitename" : "Answers",
      "sysrowid" : 5448547,
      "uri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "The remote server returned an error: (404) Not Found.",
    "Uri" : "http://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
    "PrintableUri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
    "ClickUri" : "https://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/9620/the-remote-server-returned-an-error-404-not-found.html",
    "Excerpt" : "May be the url need to return a Json? ... </restEndpointConfiguration> </coveo> </sitecore> </configuration> ... When I try to rebuild the index no error is promted inside the log files but it rema...",
    "FirstSentences" : null
  }