{
    "title" : "Coveo for Sitecore Install Error: \"One or more exceptions occurred while processing the subscribers to the 'item:saved' event.\"",
    "uri" : "http://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
    "printableUri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
    "clickUri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
    "excerpt" : "We're trying to install Coveo for Sitecore, and part-way through the package installation, we get the following exception: ... One or more exceptions occurred while processing the subscribers to th...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1138,
    "percentScore" : 75.908005,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Coveo for Sitecore Install Error: \"One or more exceptions occurred while processing the subscribers to the 'item:saved' event.\"",
      "sysauthor" : "chrisweiss",
      "sysurihash" : "qvGiuO7ñ3U8CdeRK",
      "urihash" : "qvGiuO7ñ3U8CdeRK",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160358,
      "questionaskeddatestring" : "·\n            Jun 22, 2016 at 04:38 PM ·",
      "tags" : [ "coveoforsitecore4", "sitecore8.1update2" ],
      "sysconcepts" : "sitecore ; Coveo Pro ; installation ; exceptions ; config file ; reporting ; remote ; servers ; Enterprise Search ; Beniot Lecleric ; Boolean removeOtherVersions ; IProcessingContext context ; singleInstance ; DefinitionData",
      "concepts" : "sitecore ; Coveo Pro ; installation ; exceptions ; config file ; reporting ; remote ; servers ; Enterprise Search ; Beniot Lecleric ; Boolean removeOtherVersions ; IProcessingContext context ; singleInstance ; DefinitionData",
      "printableuri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942635000,
      "permanentid" : "0e6107194ba2da94145c66c71b5a469134d68793fc462ff2ba6f65825e59",
      "syslanguage" : [ "English" ],
      "transactionid" : 160358,
      "title" : "Coveo for Sitecore Install Error: \"One or more exceptions occurred while processing the subscribers to the 'item:saved' event.\"",
      "date" : 1466985600000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Jean-François L'Heureux" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "Jean-François L'Heureux \u2666\u2666", "reidk", "Jean-François L'Heureux \u2666\u2666", "reidk", "reidk" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5448276,
      "numberofcomments" : 5,
      "size" : 84274,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911578575,
      "acceptedanswers" : 0,
      "syssize" : 84274,
      "sysdate" : 1466985600000,
      "author" : "chrisweiss",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>(I'm using Coveo for Sitecore 4 and Sitecore 8.1 Update 2)</p> \n<p>We're trying to install Coveo for Sitecore, and part-way through the package installation, we get the following exception:</p> \n<pre><code> One or more exceptions occurred while processing the subscribers to the 'item:saved' event.\n Exception[1]: System.Reflection.TargetInvocationException \n Message[1]: Exception has been thrown by the target of an invocation. \n Source[1]: mscorlib \n    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\n    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n    at Sitecore.Reflection.ReflectionUtil.CreateObject(Type type, Object[] parameters)\n    at Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)\n    at Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper)\n    at Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert)\n    at Sitecore.Analytics.Reporting.DefinitionData.RemoteWriteOnlyDefinitionsStorageProvider.Save(DefinitionData definition)\n    at Sitecore.Analytics.Pipelines.DeployDefinition.SavePageEvent.Deploy(Item item)\n    at Sitecore.Analytics.Pipelines.DeployDefinition.DeployDefinitionProcessor.Process(DeployDefinitionArgs args)\n    at (Object , Object[] )\n    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)\n    at Sitecore.Analytics.Pipelines.DeployDefinition.DeployDefinitionPipeline.<>c__DisplayClass1.<Run>b__0()\n    at Sitecore.Marketing.Core.IgnoreRecursiveCalls.Run(ID id, Action action)\n    at Sitecore.Analytics.Pipelines.DeployDefinition.DeployDefinitionPipeline.Run(Item item)\n    at Sitecore.Analytics.Data.Items.ItemEventHandler.OnItemSaved(Object sender, EventArgs args)\n    at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result) \n\n</code></pre> \n<p>AND</p> \n<pre><code> Error installing items/master/sitecore/system/Settings/Analytics/Page Events/Coveo/Document Views/Document Click/{A4113BAA-32DE-4213-8615-5B3339476915}/en/1/xml\n Exception: System.AggregateException\n Message: One or more exceptions occurred while processing the subscribers to the 'item:saved' event.\n Source: Sitecore.Kernel\n    at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result)\n    at Sitecore.Events.Event.RaiseEvent(String eventName, Object[] parameters)\n    at Sitecore.Events.Event.RaiseItemSaved(Object sender, ItemSavedEventArgs args)\n    at System.EventHandler`1.Invoke(Object sender, TEventArgs e)\n    at Sitecore.Data.Engines.EngineCommand`2.RaiseEvent[TArgs](EventHandler`1 handlers, Func`2 argsCreator)\n    at Sitecore.Data.Engines.EngineCommand`2.Execute()\n    at Sitecore.Data.Engines.DataEngine.SaveItem(Item item)\n    at Sitecore.Data.Managers.ItemProvider.SaveItem(Item item)\n    at Sitecore.Data.Managers.PipelineBasedItemProvider.ExecuteAndReturnResult[TArgs,TResult](String pipelineName, String pipelineDomain, Func`1 pipelineArgsCreator, Func`1 fallbackResult)\n    at Sitecore.Data.Managers.PipelineBasedItemProvider.SaveItem(Item item)\n    at Sitecore.Data.Items.ItemEditing.AcceptChanges(Boolean updateStatistics, Boolean silent)\n    at Sitecore.Install.Items.ItemInstaller.VersionInstaller.InstallVersion(Item version)\n    at Sitecore.Install.Items.ItemInstaller.VersionInstaller.PasteVersion(XmlNode versionXml, Item target, VersionInstallMode mode, IProcessingContext context, Boolean removeOtherVersions)\n    at Sitecore.Install.Items.ItemInstaller.InstallEntry(PackageEntry entry)\n\n</code></pre> \n<p>This shuts down the installation process and asks if we'd like to try again. Any idea how to fix this?</p>\n                </div>",
      "sitemaplastmodified" : 1466985600000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942635000,
      "questionnumber" : 8353,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "chrisweiss",
      "sitename" : "Answers",
      "sysrowid" : 5448276,
      "uri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Coveo for Sitecore Install Error: \"One or more exceptions occurred while processing the subscribers to the 'item:saved' event.\"",
    "Uri" : "http://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
    "PrintableUri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
    "ClickUri" : "https://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/8353/coveo-for-sitecore-install-error-one-or-more-excep.html",
    "Excerpt" : "We're trying to install Coveo for Sitecore, and part-way through the package installation, we get the following exception: ... One or more exceptions occurred while processing the subscribers to th...",
    "FirstSentences" : null
  }