{
    "title" : "The remote server returned an error: (401) Unauthorized.",
    "uri" : "http://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
    "printableUri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
    "clickUri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
    "excerpt" : "We have a different server for the Coveo. ... Please help me to resolve the same. ... When I open Administraton Tool, I can able to see both indexes, but still getting the issues. ... The \"No user ...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1341,
    "percentScore" : 82.40069,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "The remote server returned an error: (401) Unauthorized.",
      "sysauthor" : "Umesh Bannimatti",
      "sysurihash" : "mzvZ8yfO6czF5UsL",
      "urihash" : "mzvZ8yfO6czF5UsL",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160371,
      "questionaskeddatestring" : "·\n            Mar 04, 2016 at 12:29 AM ·",
      "tags" : [ "coveoforsitecore", "ces", "searchapi" ],
      "sysconcepts" : "sitecore credentials ; security provider ; indexing ; ticket ; SearchProvider ; p12 ; certificate ; configuration ; support team ; REST Endpoint ; impersonation rights ; troubleshoot ; CoveoDiagnosticPage ; FailedToImpersonateUsersException ; SitecoreInstanceName ; MachineName",
      "concepts" : "sitecore credentials ; security provider ; indexing ; ticket ; SearchProvider ; p12 ; certificate ; configuration ; support team ; REST Endpoint ; impersonation rights ; troubleshoot ; CoveoDiagnosticPage ; FailedToImpersonateUsersException ; SitecoreInstanceName ; MachineName",
      "printableuri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517943528000,
      "permanentid" : "036fcde0b2062eb9f71b5e392892bb1f66af529e1cc5a97d54134d87434d",
      "syslanguage" : [ "English" ],
      "transactionid" : 160371,
      "title" : "The remote server returned an error: (401) Unauthorized.",
      "date" : 1516233600000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Jean-François L'Heureux" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "Jean-François L'Heureux \u2666\u2666", "Umesh Bannimatti", "Umesh Bannimatti", "Jean-François L'Heureux \u2666\u2666", "Umesh Bannimatti", "Jean-François L'Heureux \u2666\u2666" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5449458,
      "numberofcomments" : 6,
      "size" : 87645,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911579738,
      "acceptedanswers" : 0,
      "syssize" : 87645,
      "sysdate" : 1516233600000,
      "author" : "Umesh Bannimatti",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>Hi Team,</p> \n<p>In the CoveoDiagnosticPage, I am getting the following errors.</p> \n<h2>Coveo Search REST Endpoint ():</h2> \n<p> The remote server returned an error: (401) Unauthorized</p> \n<h2>Coveo Search Web Service:</h2> \n<p> Exception Name:class CES::SearchServerException, What:class CES::SearchServerException: No user has been provided for the search request.</p> \n<h2>Coveo Security Service:</h2> \n<p> The remote server returned an error: (401) Unauthorized. </p> \n<hr> \n<h2>More Details:</h2> \n<ul> \n <li><p> We have a different server for the Coveo. </p> </li> \n <li><p> We have NOT enabled the Secure Admin Service. </p> </li> \n <li><p> We have checked the \"This installation is part of a Sitecore Integration\" check box while installing the Coveo Search API </p> </li> \n <li><p> We are able to start the Coveo Search API service. </p> </li> \n <li><p> Application Secret is same in both config.yml and Coveo.SearchProvider.Rest.config file. </p> </li> \n <li><p> Response for <a rel=\"nofollow\" href=\"http://OurInstanceName/Coveo/rest:\">http://OurInstanceName/Coveo/rest:</a> {\"totalCount\":0,\"totalCountFiltered\":0,\"duration\":798,\"indexDuration\":10,\"requestDuration\":641,\"searchUid\":\"d5c5f078-4b05-429f-a9a2-16b9a3d18b10\",\"pipeline\":\"default\",\"apiVersion\":2,\"triggers\":[],\"termsToHighlight\":{},\"phrasesToHighlight\":{},\"queryCorrections\":[],\"groupByResults\":[],\"results\":[]} </p> </li> \n <li><p> Response for <a rel=\"nofollow\" href=\"http://YourCoveoSearchApiHost:8080/rest/search\">http://YourCoveoSearchApiHost:8080/rest/search</a> { \"totalCount\" : 0, \"totalCountFiltered\" : 0, \"duration\" : 188, \"indexDuration\" : 10, \"requestDuration\" : 188, \"searchUid\" : \"fd6c26ab-b43c-4952-97af-2a5a887dde9d\", \"pipeline\" : \"default\", \"apiVersion\" : 2, \"triggers\" : [ ], \"termsToHighlight\" : { }, \"phrasesToHighlight\" : { }, \"queryCorrections\" : [ ], \"groupByResults\" : [ ], \"results\" : [ ] }</p> </li> \n</ul> \n<p>Please help me to resolve the same.</p> \n<p>Regards, Umesh</p>\n                </div>",
      "sitemaplastmodified" : 1516233600000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517943528000,
      "questionnumber" : 7516,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "Umesh Bannimatti",
      "sitename" : "Answers",
      "sysrowid" : 5449458,
      "uri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "The remote server returned an error: (401) Unauthorized.",
    "Uri" : "http://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
    "PrintableUri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
    "ClickUri" : "https://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/7516/the-remote-server-returned-an-error-401-unauthoriz.html",
    "Excerpt" : "We have a different server for the Coveo. ... Please help me to resolve the same. ... When I open Administraton Tool, I can able to see both indexes, but still getting the issues. ... The \"No user ...",
    "FirstSentences" : null
  }