{
    "title" : "Replaced the wrong instance Coveo configuration file",
    "uri" : "http://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
    "printableUri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
    "clickUri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
    "excerpt" : "Object reference not set to an instance of an object\". ... How can we resolve this issue, please suggest? ... We are going to need more context here. ... Could you provide a stacktrace? ... If wron...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1258,
    "percentScore" : 79.8099,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Replaced the wrong instance Coveo configuration file",
      "sysauthor" : "AKumar346",
      "sysurihash" : "JjpXSpUcfWmg6Pts",
      "urihash" : "JjpXSpUcfWmg6Pts",
      "numberofanswers" : 0,
      "sysuri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160370,
      "questionaskeddatestring" : "·\n            Nov 14, 2017 at 12:17 AM ·",
      "tags" : [ "wrongcoveoconfig" ],
      "sysconcepts" : "Coveo ; Sitecore Credentials ; knowing ; config ; SearchProvider ; bigger problems ; rest of the changes ; done ; SitecorePassword",
      "concepts" : "Coveo ; Sitecore Credentials ; knowing ; config ; SearchProvider ; bigger problems ; rest of the changes ; done ; SitecorePassword",
      "printableuri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517943425000,
      "permanentid" : "5e747a38e38f91ac0d511011aa390aafc3e517e8b7e37be84eb563e020e1",
      "syslanguage" : [ "English" ],
      "transactionid" : 160370,
      "title" : "Replaced the wrong instance Coveo configuration file",
      "date" : 1510617600000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "hasanswer" : "false",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "Sébastien Belzile \u2666\u2666", "François Lachance-Guillemette \u2666\u2666" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5449316,
      "numberofcomments" : 2,
      "size" : 68040,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911579596,
      "acceptedanswers" : 0,
      "syssize" : 68040,
      "sysdate" : 1510617600000,
      "author" : "AKumar346",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>\n<p>We have wrongly replace the Coveo.SearchProvider.Custom.config file of another instance, after that \"Clean Up\" links on \"Coveo Search Actions\" is giving exception \"</p>\n<h2><em>Object reference not set to an instance of an object\".</em></h2>\n<p>How can we resolve this issue, please suggest?</p>\n<p>Do we need to re-configure the \"Coveo Cloud Organization\"?</p> \n<p>\n                </div>",
      "sitemaplastmodified" : 1510617600000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517943425000,
      "questionnumber" : 13466,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "AKumar346",
      "sitename" : "Answers",
      "sysrowid" : 5449316,
      "uri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Replaced the wrong instance Coveo configuration file",
    "Uri" : "http://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
    "PrintableUri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
    "ClickUri" : "https://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/13466/replaced-the-wrong-instance-coveo-configuration-fi.html",
    "Excerpt" : "Object reference not set to an instance of an object\". ... How can we resolve this issue, please suggest? ... We are going to need more context here. ... Could you provide a stacktrace? ... If wron...",
    "FirstSentences" : null
  }