{
    "title" : "Not able to rebuild the Coveo index, getting the below exception",
    "uri" : "http://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
    "printableUri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
    "clickUri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
    "excerpt" : "coveo for sitecore ... Not able to rebuild the Coveo index, getting the below exception ... Job started: Index_Update_IndexName=Coveo_master_index|#Exception: System.Reflection.TargetInvocationExce...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1240,
    "percentScore" : 79.23686,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Not able to rebuild the Coveo index, getting the below exception",
      "sysauthor" : "Versha",
      "sysurihash" : "OmPkUñJywhuñynqS",
      "urihash" : "OmPkUñJywhuñynqS",
      "numberofanswers" : 0,
      "sysuri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160369,
      "questionaskeddatestring" : "·\n            Oct 12, 2017 at 06:09 AM ·",
      "tags" : [ "coveo for sitecore" ],
      "sysconcepts" : "coveo ; exception ; sitecore ; special manipulations ; Look ; Heureux ; Jean-François ; NullReferenceException ; invocation ; TargetInvocationException ; Reflection",
      "concepts" : "coveo ; exception ; sitecore ; special manipulations ; Look ; Heureux ; Jean-François ; NullReferenceException ; invocation ; TargetInvocationException ; Reflection",
      "printableuri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517943380000,
      "permanentid" : "9243339e59e0b57b21af8a7fd60de9c9349db6ee753c4e9501948cab32a8",
      "syslanguage" : [ "English" ],
      "transactionid" : 160369,
      "title" : "Not able to rebuild the Coveo index, getting the below exception",
      "date" : 1507766400000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "hasanswer" : "false",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "Sébastien Belzile \u2666\u2666", "Jean-François L'Heureux \u2666\u2666" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5449257,
      "numberofcomments" : 2,
      "size" : 68931,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911579537,
      "acceptedanswers" : 0,
      "syssize" : 68931,
      "sysdate" : 1507766400000,
      "author" : "Versha",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>\n<p>Job started: Index_Update_IndexName=Coveo_master_index|#Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object. at System.Object.GetType() at Coveo.Framework.CNL.Precondition.InstanceOf[TExpected](Object p_Parameter, String p_ParameterName) at Coveo.Framework.CNL.Precondition.InstanceOf[TExpected](Object p_Parameter, Func`1 p_ParameterExpression) at Coveo.SearchProvider.Utils.ProviderUpdateContextTypeHandler.CreateInstance(ISitecoreFeaturesResolver p_SitecoreFeaturesResolver, Object[] p_Arguments) at Coveo.Framework.ObjectFactory.TypeHandlers.BaseCreateInstanceTypeHandler`1.Coveo.Framework.ObjectFactory.ICreateInstanceTypeHandler.CreateObjectInstance(ISitecoreFeaturesResolver p_SitecoreFeaturesResolver, Object[] p_Arguments) at Coveo.Framework.ObjectFactory.ObjectFactory.CreateInstance[T](Object[] p_Arguments) at Coveo.SearchProvider.ProviderIndex.CreateUpdateContext() at Coveo.SearchProvider.ProviderIndex.<Rebuild>b__42() at Coveo.SearchProvider.ProviderIndex.TryPerformIndexingOperation(IndexingOptions p_IndexingOptions, Action p_Action) at Coveo.SearchProvider.ProviderIndex.Rebuild() --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj) at Sitecore.Jobs.JobRunner.RunMethod(JobArgs args) at (Object , Object[] ) at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) at Sitecore.Jobs.Job.ThreadEntry(Object state)</p> \n<p>\n                </div>",
      "sitemaplastmodified" : 1507766400000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517943380000,
      "questionnumber" : 13094,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "Versha",
      "sitename" : "Answers",
      "sysrowid" : 5449257,
      "uri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Not able to rebuild the Coveo index, getting the below exception",
    "Uri" : "http://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
    "PrintableUri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
    "ClickUri" : "https://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/13094/not-able-to-rebuild-the-coveo-index-getting-the-be.html",
    "Excerpt" : "coveo for sitecore ... Not able to rebuild the Coveo index, getting the below exception ... Job started: Index_Update_IndexName=Coveo_master_index|#Exception: System.Reflection.TargetInvocationExce...",
    "FirstSentences" : null
  }