{
    "title" : "Handling Exceptions",
    "uri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
    "printableUri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
    "clickUri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
    "uniqueId" : "42.37833$https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
    "excerpt" : "Exceptions can arise during a crawling run for a variety of reasons. ... It is important to handle the exceptions correctly in order for the connector to be robust and efficient. ... It is also imp...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 0,
    "percentScore" : 0.0,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Handling Exceptions",
      "sysauthor" : "Coveo Doc Team",
      "sysurihash" : "IhgzhgqXcgE0cQzZ",
      "urihash" : "IhgzhgqXcgE0cQzZ",
      "sysuri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
      "systransactionid" : 160494,
      "ohdoctype" : "Help Topic",
      "tags" : [ "Open connector", "Exception" ],
      "sysconcepts" : "exceptions ; crawling ; connector ; robust ; CustomCrawler class ; automatically deletion ; ignored folder ; usually connection ; variety of reasons ; API of the target ; CrawlerStopRefreshException",
      "ohplatformfull" : [ "Coveo Platform 6.5" ],
      "concepts" : "exceptions ; crawling ; connector ; robust ; CustomCrawler class ; automatically deletion ; ignored folder ; usually connection ; variety of reasons ; API of the target ; CrawlerStopRefreshException",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517971594000,
      "permanentid" : "1967ac9ff41d1825e7ccce8c8b6a3c962ed5c07f1b15bb2d75e089a73a76",
      "syslanguage" : [ "English" ],
      "transactionid" : 160494,
      "title" : "Handling Exceptions",
      "date" : 1517971577000,
      "objecttype" : "Online Help Topic",
      "ohtopicrelativelink" : "Developer/Handling_Exceptions.htm",
      "audience" : [ "Developer" ],
      "ohbreadcrumb" : "Coveo Platform 6.5 > Developer Help > Open Connector API > Advanced Topics",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5454937,
      "size" : 12391,
      "sysdocumenttype" : "WebPage",
      "clickableuri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
      "ohplatformname" : [ "Coveo Platform" ],
      "syssource" : "ohces65en",
      "orderingid" : 212384774710055629,
      "syssize" : 12391,
      "sysdate" : 1517971577000,
      "ohplatformtype" : [ "On-premises" ],
      "author" : "Coveo Doc Team",
      "source" : "ohces65en",
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517971594000,
      "ohplatformrelativepath" : "/en/ces/6.5",
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "https://onlinehelp.coveo.com/en/ces/6.5/sitemap.xml",
      "sitename" : "Online Help - Platform 6.5",
      "sysrowid" : 5454937,
      "uri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
      "ohtopictitle" : "Handling Exceptions",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ],
      "ohplatformversion" : [ "6.5" ]
    },
    "Title" : "Handling Exceptions",
    "Uri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
    "PrintableUri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
    "ClickUri" : "https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
    "UniqueId" : "42.37833$https://onlinehelp.coveo.com/en/ces/6.5/Developer/Handling_Exceptions.htm",
    "Excerpt" : "Exceptions can arise during a crawling run for a variety of reasons. ... It is important to handle the exceptions correctly in order for the connector to be robust and efficient. ... It is also imp...",
    "FirstSentences" : null
  }