{
    "title" : "SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA13200000007Lr",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
    "excerpt" : "A source appears to be unable to connect to Salesforce in the Cloud admin : ... Message in the Cloud Admin when you hover the source : ... Cause ... The crawling user does not have the Salesforce P...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1446,
    "percentScore" : 85.56588,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin",
      "sysurihash" : "QAavWXUJYOt8rEwl",
      "urihash" : "QAavWXUJYOt8rEwl",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin\" uri=\"https://na61.salesforce.com/kA13200000007Lr\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "<p>Enable the Permission Enable All modify Data in Salesforce. <br><br>In SF<br>From Setup Search box - &gt; Permission settings - &gt; New -&gt; Check the box Modify all data - &gt; Give the crawling user this permission. <br><br><a href=\"https://help.salesforce.com/HTViewHelpDoc?id=perm_sets_assigning.htm&amp;language=en_US\" target=\"_blank\">Assign Permission Sets to a Single User</a><br> </p>\n\n<p>Just to make sure the sources are using a fresh authentication, it&#39;s best practice to revoke the oauth connected apps<br><img src=\"https://coveord.atlassian.net/wiki/download/attachments/7897328/image2016-1-29%2016%3A43%3A6.png?version=1&amp;modificationDate=1454103786410&amp;api=v2\"></img><br><br>- Log in Salesforce as the crawling user <br><br>- go to my settings&gt;personal&gt;connection&gt;revoke <br><br>- click revoke on all Coveo OAuth Connected Apps <br><br>- go to your org in the cloudUI <br>https://cloud.coveo.com/#content/sources <br><br>- click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials. <br><br>- Re-login with the appropriate crawling user. <br><br>- You should get a confirmation page requesting that you confirm access to Salesforce for this user. <br><br>- Click Yes. </p>",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
      "sflastpublisheddate" : 1470750418000,
      "systransactionid" : 161139,
      "sfurlname" : "1325",
      "sfsystemmodstamp" : 1518090402000,
      "sfisvisibleinapp" : "true",
      "sysconcepts" : "crawling user ; Cloud admin ; Salesforce Permission ; connected apps ; fresh authentication ; account Config ; requesting ; confirmation",
      "sfkbversionnumber" : "5",
      "concepts" : "crawling user ; Cloud admin ; Salesforce Permission ; connected apps ; fresh authentication ; account Config ; requesting ; confirmation",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka132000000CjvdAAC",
      "sysindexeddate" : 1518187567000,
      "sfknowledgearticleid" : "kA13200000007LrCAI",
      "sfcreatedbyid" : "005320000051vaDAAQ",
      "sfconnectorc" : "N/A",
      "permanentid" : "d89da47e42a90b4626f3db8b0c2059b2380ab01659bc26ea8d3e33260c83",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin",
      "sfversionnumber" : 5,
      "sfarticlenumber" : "000001325",
      "date" : 1518090402000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA13200000007Lr\"], \"sflastmodifiedbyname\": [\"Steve DiMillo\"], \"kav_coveo_version__c__html_stripped\": [\"\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Coveo Enterprise Search;All|Salesforce\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/005320000051vaDAAQ\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"005320000051vaDAAQ\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/005320000051vaDAAQ\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin\\\" uri=\\\"https://na61.salesforce.com/kA13200000007Lr\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin\"], \"kav_isvisibleincsp\": [true], \"hashtmlversion\": [true], \"kav_versionnumber\": [5], \"sfcreatedbyname\": [\"Yan Bussieres\"], \"sflastpublisheddate\": [1470750418], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"\\n The crawling user does not have the Salesforce Permission to modify all data.\\u00a0 \\n \\n More info on Sf Crawling account  Config\\u00a0 \\n \\n //////////////////////////////\\u00a0 \\n Index Logs, for the Salesforce Source :\\u00a0 \\n \\n IMPORTANT 03:45:28 PM Incremental refresh of source Salesforce - coveo@XXXX.com was stopped. Default Salesforce - coveo@XXXX.com\\u00a0 \\n \\n ERROR 03:45:28 PM INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com\\u00a0 \\n \\n ERROR 03:45:28 PM Error with ID 'SALESFORCE_UNABLE_TO_CONNECT': INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com\\u00a0 \\n \\n //////////////////////////////\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1470750418], \"sfsystemmodstamp\": [1518090402], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Coveo Enterprise Search;Salesforce\"], \"clickableuri\": [\"https://na61.salesforce.com/kA13200000007Lr\"], \"sftitle\": [\"SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin\"], \"kav_owner.id\": [\"005320000051vaDAAQ\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA13200000007LrCAI\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"<br>The crawling user does not have the Salesforce Permission to modify all data.\\u00a0<br><br>More info on Sf Crawling account <a href=\\\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/creating_a_dedicated_salesforce_crawling_account.htm\\\" target=\\\"_blank\\\">Config\\u00a0</a><br><br>//////////////////////////////\\u00a0<br>Index Logs, for the Salesforce Source :\\u00a0<br><br>IMPORTANT 03:45:28 PM Incremental refresh of source Salesforce - coveo@XXXX.com was stopped. Default Salesforce - coveo@XXXX.com\\u00a0<br><br>ERROR 03:45:28 PM INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com\\u00a0<br><br>ERROR 03:45:28 PM Error with ID &#39;SALESFORCE_UNABLE_TO_CONNECT&#39;: INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com\\u00a0<br><br>//////////////////////////////\"], \"sfislatestversion\": [true], \"sfcausec\": [\"<br>The crawling user does not have the Salesforce Permission to modify all data.\\u00a0<br><br>More info on Sf Crawling account <a href=\\\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/creating_a_dedicated_salesforce_crawling_account.htm\\\" target=\\\"_blank\\\">Config\\u00a0</a><br><br>//////////////////////////////\\u00a0<br>Index Logs, for the Salesforce Source :\\u00a0<br><br>IMPORTANT 03:45:28 PM Incremental refresh of source Salesforce - coveo@XXXX.com was stopped. Default Salesforce - coveo@XXXX.com\\u00a0<br><br>ERROR 03:45:28 PM INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com\\u00a0<br><br>ERROR 03:45:28 PM Error with ID &#39;SALESFORCE_UNABLE_TO_CONNECT&#39;: INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com\\u00a0<br><br>//////////////////////////////\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"1325\"], \"ka_id\": [\"kA13200000007LrCAI\"], \"kav_datacategoryselections.datacategoryname\": [\"Coveo_Enterprise_Search;Salesforce;Configuration\"], \"coveo_url\": [\"https://na61.salesforce.com/kA13200000007Lr\"], \"kav_urlname\": [\"1325\"], \"kav_dc_expanded_product\": [\"All;All|Coveo Enterprise Search;All|Salesforce\"], \"foldingcollection\": [\"13432447bd5367aaa55fd545ff308e8af154ac5e8364fe5b061257d576de\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> <p>A source appears to be unable to connect to Salesforce in the Cloud admin :\\u00a0</p>\\n\\n<p>Message in the Cloud Admin when you hover the source :\\u00a0<br><br>SALESFORCE_UNABLE_TO_CONNECT<br><img alt=\\\"User-added image\\\" height=\\\"81\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka132000000Cjvd&amp;feoid=00N32000002zy14&amp;refid=0EM320000005fH4\\\" width=\\\"500\\\"></img></p></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td>Salesforce</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1470750418</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> <br>The crawling user does not have the Salesforce Permission to modify all data.\\u00a0<br><br>More info on Sf Crawling account <a href=\\\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/creating_a_dedicated_salesforce_crawling_account.htm\\\" target=\\\"_blank\\\">Config\\u00a0</a><br><br>//////////////////////////////\\u00a0<br>Index Logs, for the Salesforce Source :\\u00a0<br><br>IMPORTANT 03:45:28 PM Incremental refresh of source Salesforce - coveo@XXXX.com was stopped. Default Salesforce - coveo@XXXX.com\\u00a0<br><br>ERROR 03:45:28 PM INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com\\u00a0<br><br>ERROR 03:45:28 PM Error with ID &#39;SALESFORCE_UNABLE_TO_CONNECT&#39;: INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com\\u00a0<br><br>//////////////////////////////</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> <p>Enable the Permission Enable All modify Data in Salesforce.\\u00a0<br><br>In SF<br>From Setup Search box\\u00a0- &gt; Permission settings - &gt; New -&gt; Check the box Modify all data - &gt; Give the crawling user this permission.\\u00a0<br><br><a href=\\\"https://help.salesforce.com/HTViewHelpDoc?id=perm_sets_assigning.htm&amp;language=en_US\\\" target=\\\"_blank\\\">Assign Permission Sets to a Single User</a><br>\\u00a0</p>\\n\\n<p>Just to make sure the sources are using a fresh authentication, it&#39;s best practice to revoke the oauth connected apps<br><img src=\\\"https://coveord.atlassian.net/wiki/download/attachments/7897328/image2016-1-29%2016%3A43%3A6.png?version=1&amp;modificationDate=1454103786410&amp;api=v2\\\"></img><br><br>- Log in Salesforce as the crawling user\\u00a0<br><br>- go to my settings&gt;personal&gt;connection&gt;revoke\\u00a0<br><br>- click revoke on all Coveo OAuth Connected Apps\\u00a0<br><br>- go to your org in the cloudUI\\u00a0<br>https://cloud.coveo.com/#content/sources\\u00a0<br><br>- click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials.\\u00a0<br><br>- Re-login with the appropriate crawling user.\\u00a0<br><br>- You should get a confirmation page requesting that you confirm access to Salesforce for this user.\\u00a0<br><br>- Click Yes.\\u00a0</p></div>     </div>   </body> </html>\"], \"kav_product__c\": [\"Salesforce\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"005320000051vaDAAQ\"], \"kav_description__c__html_stripped\": [\"A source appears to be unable to connect to Salesforce in the Cloud admin :\\u00a0\\n \\n\\n Message in the Cloud Admin when you hover the source :\\u00a0 \\n \\n SALESFORCE_UNABLE_TO_CONNECT \\n \\n\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA13200000007LrCAI\"], \"sfknowledgearticleid\": [\"kA13200000007LrCAI\"], \"sfownername\": [\"Yan Bussieres\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1470750200], \"language\": [\"English\"], \"coveo_foldingchild\": [\"3deaad36d958c9ba2e66abda99faf8128df5c228f22ae677ca1f8650b305\"], \"sfownerid\": [\"005320000051vaDAAQ\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1518090402], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Yan Bussieres\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"CAD\"], \"sfisdeleted\": [false], \"extractedsize\": [3722], \"size\": [6704], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"<p>A source appears to be unable to connect to Salesforce in the Cloud admin :\\u00a0</p>\\n\\n<p>Message in the Cloud Admin when you hover the source :\\u00a0<br><br>SALESFORCE_UNABLE_TO_CONNECT<br><img alt=\\\"User-added image\\\" height=\\\"81\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka132000000Cjvd&amp;feoid=00N32000002zy14&amp;refid=0EM320000005fH4\\\" width=\\\"500\\\"></img></p>\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1470750418], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka132000000CjvdAAC\"], \"kav_currencyisocode\": [\"CAD\"], \"sfproductc\": [\"Salesforce\"], \"foldingparent\": [\"3deaad36d958c9ba2e66abda99faf8128df5c228f22ae677ca1f8650b305\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"5003200000zT8twAAC\"], \"sfkbversionnumber\": [5], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"<p>Enable the Permission Enable All modify Data in Salesforce.\\u00a0<br><br>In SF<br>From Setup Search box\\u00a0- &gt; Permission settings - &gt; New -&gt; Check the box Modify all data - &gt; Give the crawling user this permission.\\u00a0<br><br><a href=\\\"https://help.salesforce.com/HTViewHelpDoc?id=perm_sets_assigning.htm&amp;language=en_US\\\" target=\\\"_blank\\\">Assign Permission Sets to a Single User</a><br>\\u00a0</p>\\n\\n<p>Just to make sure the sources are using a fresh authentication, it&#39;s best practice to revoke the oauth connected apps<br><img src=\\\"https://coveord.atlassian.net/wiki/download/attachments/7897328/image2016-1-29%2016%3A43%3A6.png?version=1&amp;modificationDate=1454103786410&amp;api=v2\\\"></img><br><br>- Log in Salesforce as the crawling user\\u00a0<br><br>- go to my settings&gt;personal&gt;connection&gt;revoke\\u00a0<br><br>- click revoke on all Coveo OAuth Connected Apps\\u00a0<br><br>- go to your org in the cloudUI\\u00a0<br>https://cloud.coveo.com/#content/sources\\u00a0<br><br>- click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials.\\u00a0<br><br>- Re-login with the appropriate crawling user.\\u00a0<br><br>- You should get a confirmation page requesting that you confirm access to Salesforce for this user.\\u00a0<br><br>- Click Yes.\\u00a0</p>\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000HBkVAAW;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000HBkXAAW;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000HBkWAAW\"], \"kav_id\": [\"ka132000000CjvdAAC\"], \"sfresolutionc\": [\"<p>Enable the Permission Enable All modify Data in Salesforce.\\u00a0<br><br>In SF<br>From Setup Search box\\u00a0- &gt; Permission settings - &gt; New -&gt; Check the box Modify all data - &gt; Give the crawling user this permission.\\u00a0<br><br><a href=\\\"https://help.salesforce.com/HTViewHelpDoc?id=perm_sets_assigning.htm&amp;language=en_US\\\" target=\\\"_blank\\\">Assign Permission Sets to a Single User</a><br>\\u00a0</p>\\n\\n<p>Just to make sure the sources are using a fresh authentication, it&#39;s best practice to revoke the oauth connected apps<br><img src=\\\"https://coveord.atlassian.net/wiki/download/attachments/7897328/image2016-1-29%2016%3A43%3A6.png?version=1&amp;modificationDate=1454103786410&amp;api=v2\\\"></img><br><br>- Log in Salesforce as the crawling user\\u00a0<br><br>- go to my settings&gt;personal&gt;connection&gt;revoke\\u00a0<br><br>- click revoke on all Coveo OAuth Connected Apps\\u00a0<br><br>- go to your org in the cloudUI\\u00a0<br>https://cloud.coveo.com/#content/sources\\u00a0<br><br>- click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials.\\u00a0<br><br>- Re-login with the appropriate crawling user.\\u00a0<br><br>- You should get a confirmation page requesting that you confirm access to Salesforce for this user.\\u00a0<br><br>- Click Yes.\\u00a0</p>\"], \"foldingchild\": [\"3deaad36d958c9ba2e66abda99faf8128df5c228f22ae677ca1f8650b305\"], \"sfcreateddate\": [1470750200], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1518090402], \"kav_summary__html_stripped\": [\"\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Coveo Enterprise Search;Salesforce\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2;2\"], \"concepts\": [\"crawling user ; Cloud admin ; Salesforce Permission ; connected apps ; fresh authentication ; account Config ; requesting ; confirmation\"], \"sfkbid\": [\"kA13200000007LrCAI\"], \"kav_firstpublisheddate\": [1460646953], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"13432447bd5367aaa55fd545ff308e8af154ac5e8364fe5b061257d576de\"], \"sffirstpublisheddate\": [1460646953], \"sflastmodifieddate\": [1470750418], \"kav_resolution__c__html_stripped\": [\"Enable the Permission Enable All modify Data in Salesforce.\\u00a0 \\n \\n In SF \\n From Setup Search box\\u00a0- > Permission settings - > New -> Check the box Modify all data - > Give the crawling user this permission.\\u00a0 \\n \\n Assign Permission Sets to a Single User \\n \\u00a0\\n \\n\\n Just to make sure the sources are using a fresh authentication, it's best practice to revoke the oauth connected apps \\n  \\n \\n - Log in Salesforce as the crawling user\\u00a0 \\n \\n - go to my settings>personal>connection>revoke\\u00a0 \\n \\n - click revoke on all Coveo OAuth Connected Apps\\u00a0 \\n \\n - go to your org in the cloudUI\\u00a0 \\n https://cloud.coveo.com/#content/sources\\u00a0 \\n \\n - click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials.\\u00a0 \\n \\n - Re-login with the appropriate crawling user.\\u00a0 \\n \\n - You should get a confirmation page requesting that you confirm access to Salesforce for this user.\\u00a0 \\n \\n - Click Yes.\\u00a0\\n\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005YwSuAAK\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Yan Bussieres\"], \"sfarticlenumber\": [\"000001325\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o32000000HBkVAAW;02o32000000HBkXAAW;02o32000000HBkWAAW\"], \"kav_description__c\": [\"<p>A source appears to be unable to connect to Salesforce in the Cloud admin :\\u00a0</p>\\n\\n<p>Message in the Cloud Admin when you hover the source :\\u00a0<br><br>SALESFORCE_UNABLE_TO_CONNECT<br><img alt=\\\"User-added image\\\" height=\\\"81\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka132000000Cjvd&amp;feoid=00N32000002zy14&amp;refid=0EM320000005fH4\\\" width=\\\"500\\\"></img></p>\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka132000000CjvdAAC\"], \"kav_articlenumber__stripped\": [\"1325\"], \"sfversionnumber\": [5], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_validationstatus\": [\"Reviewed\"], \"coveo_foldingparent\": [\"3deaad36d958c9ba2e66abda99faf8128df5c228f22ae677ca1f8650b305\"], \"collection\": [\"default\"], \"sfsourceid\": [\"5003200000zT8twAAC\"], \"date\": [1518090402], \"kav_lastmodifiedby.id\": [\"00532000005YwSuAAK\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Product;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00532000005YwSuAAK\"], \"kav_lastmodifiedby.name\": [\"Steve DiMillo\"], \"kav_articlenumber\": [\"000001325\"], \"permanentid\": [\"d89da47e42a90b4626f3db8b0c2059b2380ab01659bc26ea8d3e33260c83\"]}",
      "sflastmodifiedbyid" : "00532000005YwSuAAK",
      "sfproductc" : "Salesforce",
      "syssfownerid" : "005320000051vaDAAQ",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin",
      "rowid" : 5492812,
      "syssfcreatedbyid" : "005320000051vaDAAQ",
      "sfdescriptionc" : "<p>A source appears to be unable to connect to Salesforce in the Cloud admin : </p>\n\n<p>Message in the Cloud Admin when you hover the source : <br><br>SALESFORCE_UNABLE_TO_CONNECT<br><img alt=\"User-added image\" height=\"81\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka132000000Cjvd&amp;feoid=00N32000002zy14&amp;refid=0EM320000005fH4\" width=\"500\"></img></p>",
      "size" : 6704,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1470750200000,
      "sfsourceid" : "5003200000zT8twAAC",
      "clickableuri" : "https://na61.salesforce.com/kA13200000007Lr",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "005320000051vaDAAQ",
      "orderingid" : 212384990660371618,
      "sfpublishstatus" : "Online",
      "syssize" : 6704,
      "sysdate" : 1518090402000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin\" uri=\"https://na61.salesforce.com/kA13200000007Lr\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "CAD",
      "sfkbid" : "kA13200000007LrCAI",
      "sfcausec" : "<br>The crawling user does not have the Salesforce Permission to modify all data. <br><br>More info on Sf Crawling account <a href=\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/creating_a_dedicated_salesforce_crawling_account.htm\" target=\"_blank\">Config </a><br><br>////////////////////////////// <br>Index Logs, for the Salesforce Source : <br><br>IMPORTANT 03:45:28 PM Incremental refresh of source Salesforce - coveo@XXXX.com was stopped. Default Salesforce - coveo@XXXX.com <br><br>ERROR 03:45:28 PM INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com <br><br>ERROR 03:45:28 PM Error with ID &#39;SALESFORCE_UNABLE_TO_CONNECT&#39;: INSUFFICIENT_ACCESS: use of the Metadata API requires a user with the ModifyAllData permission Default Salesforce - coveo@XXXX.com <br><br>//////////////////////////////",
      "sfdcexpandedproduct" : "All;All|Coveo Enterprise Search;All|Salesforce",
      "syssfcreateddate" : 1470750200000,
      "sflastmodifieddate" : 1470750418000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Steve DiMillo",
      "collection" : "default",
      "sfdcproduct" : [ "Coveo Enterprise Search", "Salesforce" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187567000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Yan Bussieres",
      "sysclickableuri" : "https://na61.salesforce.com/kA13200000007Lr",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1460646953000,
      "sfownername" : "Yan Bussieres",
      "sitename" : "Community",
      "sysrowid" : 5492812,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "SALESFORCE_UNABLE_TO_CONNECT error in Cloud Admin",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA13200000007Lr",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA13200000007LrCAI/language:en_US",
    "Excerpt" : "A source appears to be unable to connect to Salesforce in the Cloud admin : ... Message in the Cloud Admin when you hover the source : ... Cause ... The crawling user does not have the Salesforce P...",
    "FirstSentences" : null
  }