{
    "title" : "Cannot Connect to Coveo Cloud Platform",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA132000000L7ZQ",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
    "excerpt" : "You have difficulties authenticating on Coveo Cloud Platform after receiving your invite. ... You also have this error showing on the page when you try to connect: Sorry, but we're having trouble s...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1386,
    "percentScore" : 83.77184,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Cannot Connect to Coveo Cloud Platform",
      "sfsummary" : "You cannot connect or authenticate to the Coveo Cloud platform and it gives you an error.",
      "sysurihash" : "ð0QD8GmptTPtGhKw",
      "urihash" : "ð0QD8GmptTPtGhKw",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Cannot Connect to Coveo Cloud Platform\" uri=\"https://na61.salesforce.com/kA132000000L7ZQ\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "Verify that you are using one of the provider supported. If you are using one of the three authentication providers and are still experinecing problems connecting, please<a href=\"https://support.coveo.com/s/login\" target=\"_blank\"> open a Coveo support case</a>.<br><br>If you are not using one of the supported provider, contact your account owner or client executive and ask them to send a new invite to an account you possess with one of the supported authentication provider.",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
      "sflastpublisheddate" : 1480523731000,
      "systransactionid" : 161138,
      "sfurlname" : "1894",
      "sfsystemmodstamp" : 1517399256000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Cloud V2",
      "sysconcepts" : "authentication providers ; Coveo Cloud Platform ; account ; client executive ; problems connecting ; request ; trouble ; Resolution",
      "sfkbversionnumber" : "2",
      "concepts" : "authentication providers ; Coveo Cloud Platform ; account ; client executive ; problems connecting ; request ; trouble ; Resolution",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka132000000LIYJAA4",
      "sysindexeddate" : 1518187515000,
      "sfknowledgearticleid" : "kA132000000L7ZQCA0",
      "sfcreatedbyid" : "00532000005Jm9iAAC",
      "sfconnectorc" : "N/A",
      "permanentid" : "dda0aa17bd6148df01cbce21b6c5a9c3d7c095f8dbc88ae34e904f67e365",
      "syslanguage" : [ "English" ],
      "transactionid" : 161138,
      "sfisvisibleinprm" : "true",
      "title" : "Cannot Connect to Coveo Cloud Platform",
      "sfversionnumber" : 2,
      "sfarticlenumber" : "000001894",
      "date" : 1517399256000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA132000000L7ZQ\"], \"sflastmodifiedbyname\": [\"Michael Carter\"], \"kav_coveo_version__c__html_stripped\": [\"Cloud V2\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Cloud Platform;All|Sitecore\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005Jm9iAAC\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00532000005Jm9iAAC\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Cannot Connect to Coveo Cloud Platform\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005Jm9iAAC\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Cannot Connect to Coveo Cloud Platform\\\" uri=\\\"https://na61.salesforce.com/kA132000000L7ZQ\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Cannot Connect to Coveo Cloud Platform\"], \"kav_isvisibleincsp\": [true], \"sfcreateddate\": [1480523106], \"hashtmlversion\": [true], \"kav_versionnumber\": [2], \"sfcreatedbyname\": [\"Patrick Meunier\"], \"sflastpublisheddate\": [1480523731], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"The Coveo Cloud V2 platform accepts only three authentication provider at the moment:\\n Google Microsoft Office365 Salesforce\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1480523731], \"sfsystemmodstamp\": [1517399256], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Cloud Platform;Sitecore\"], \"kav_resolution__c__html_stripped\": [\"Verify that you are using one of the provider supported. If you are using one of the three authentication providers and are still experinecing problems connecting, please  open a Coveo support case . \\n \\n If you are not using one of the supported provider, contact your account owner or client executive and ask them to send a new invite to an account you possess with one of the supported authentication provider.\"], \"clickableuri\": [\"https://na61.salesforce.com/kA132000000L7ZQ\"], \"sftitle\": [\"Cannot Connect to Coveo Cloud Platform\"], \"kav_owner.id\": [\"00532000005Jm9iAAC\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA132000000L7ZQCA0\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"The Coveo Cloud V2 platform accepts only three authentication provider at the moment:\\n<ol><li>Google</li><li>Microsoft Office365</li><li>Salesforce</li></ol>\"], \"sfislatestversion\": [true], \"sfcausec\": [\"The Coveo Cloud V2 platform accepts only three authentication provider at the moment:\\n<ol><li>Google</li><li>Microsoft Office365</li><li>Salesforce</li></ol>\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"1894\"], \"ka_id\": [\"kA132000000L7ZQCA0\"], \"kav_datacategoryselections.datacategoryname\": [\"Cloud_Platform;Configuration;Sitecore\"], \"coveo_url\": [\"https://na61.salesforce.com/kA132000000L7ZQ\"], \"kav_urlname\": [\"1894\"], \"kav_dc_expanded_product\": [\"All;All|Cloud Platform;All|Sitecore\"], \"foldingcollection\": [\"61bbb0e5658c2d017d2f475013df2fc9d0d5d30a3ac8cd00cbaa79686a42\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> You have difficulties authenticating on Coveo Cloud Platform after receiving your invite.<br><br>You also have this error showing on the page when you try to connect:\\n<pre class=\\\"ckeditor_codeblock\\\">\\nSorry, but we&#39;re having trouble signing you in. We received a bad request.</pre>\\n<br><br><br><br>\\u00a0</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1480523731</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> The Coveo Cloud V2 platform accepts only three authentication provider at the moment:\\n<ol><li>Google</li><li>Microsoft Office365</li><li>Salesforce</li></ol></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> Verify that you are using one of the provider supported. If you are using one of the three authentication providers and are still experinecing problems connecting, please<a href=\\\"https://support.coveo.com/s/login\\\" target=\\\"_blank\\\"> open a Coveo support case</a>.<br><br>If you are not using one of the supported provider, contact your account owner or client executive and ask them to send a new invite to an account you possess with one of the supported authentication provider.</div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00532000005Jm9iAAC\"], \"kav_description__c__html_stripped\": [\"You have difficulties authenticating on Coveo Cloud Platform after receiving your invite. \\n \\n You also have this error showing on the page when you try to connect:\\n \\nSorry, but we're having trouble signing you in. We received a bad request. \\n \\n \\n \\n \\n \\u00a0\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA132000000L7ZQCA0\"], \"sfknowledgearticleid\": [\"kA132000000L7ZQCA0\"], \"sfownername\": [\"Patrick Meunier\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1480523106], \"language\": [\"English\"], \"coveo_foldingchild\": [\"436e07f628dff691bf6c671839d9dc47e413e0b709d95664c890a84c5b9a\"], \"sfownerid\": [\"00532000005Jm9iAAC\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1517399256], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Patrick Meunier\"], \"sfcoveoversionc\": [\"Cloud V2\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"CAD\"], \"sfisdeleted\": [false], \"extractedsize\": [1850], \"size\": [4249], \"kav_summary\": [\"You cannot connect or authenticate to the Coveo Cloud platform and it gives you an error.\"], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"You have difficulties authenticating on Coveo Cloud Platform after receiving your invite.<br><br>You also have this error showing on the page when you try to connect:\\n<pre class=\\\"ckeditor_codeblock\\\">\\nSorry, but we&#39;re having trouble signing you in. We received a bad request.</pre>\\n<br><br><br><br>\\u00a0\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1480523731], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka132000000LIYJAA4\"], \"kav_currencyisocode\": [\"CAD\"], \"foldingparent\": [\"436e07f628dff691bf6c671839d9dc47e413e0b709d95664c890a84c5b9a\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"50032000016t6DPAAY\"], \"sfkbversionnumber\": [2], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"Verify that you are using one of the provider supported. If you are using one of the three authentication providers and are still experinecing problems connecting, please<a href=\\\"https://support.coveo.com/s/login\\\" target=\\\"_blank\\\"> open a Coveo support case</a>.<br><br>If you are not using one of the supported provider, contact your account owner or client executive and ask them to send a new invite to an account you possess with one of the supported authentication provider.\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000pqjTAAQ;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000pqjSAAQ;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000pqjcAAA\"], \"kav_id\": [\"ka132000000LIYJAA4\"], \"sfresolutionc\": [\"Verify that you are using one of the provider supported. If you are using one of the three authentication providers and are still experinecing problems connecting, please<a href=\\\"https://support.coveo.com/s/login\\\" target=\\\"_blank\\\"> open a Coveo support case</a>.<br><br>If you are not using one of the supported provider, contact your account owner or client executive and ask them to send a new invite to an account you possess with one of the supported authentication provider.\"], \"foldingchild\": [\"436e07f628dff691bf6c671839d9dc47e413e0b709d95664c890a84c5b9a\"], \"sfsummary\": [\"You cannot connect or authenticate to the Coveo Cloud platform and it gives you an error.\"], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1517399256], \"kav_summary__html_stripped\": [\"You cannot connect or authenticate to the Coveo Cloud platform and it gives you an error.\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Cloud Platform;Sitecore\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2;2\"], \"concepts\": [\"authentication providers ; Coveo Cloud Platform ; account ; client executive ; problems connecting ; request ; trouble ; Resolution\"], \"sfkbid\": [\"kA132000000L7ZQCA0\"], \"kav_firstpublisheddate\": [1479854048], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"61bbb0e5658c2d017d2f475013df2fc9d0d5d30a3ac8cd00cbaa79686a42\"], \"sffirstpublisheddate\": [1479854048], \"sflastmodifieddate\": [1480523731], \"kav_coveo_version__c\": [\"Cloud V2\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000004vbsoAAA\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Patrick Meunier\"], \"sfarticlenumber\": [\"000001894\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o32000000pqjTAAQ;02o32000000pqjSAAQ;02o32000000pqjcAAA\"], \"kav_description__c\": [\"You have difficulties authenticating on Coveo Cloud Platform after receiving your invite.<br><br>You also have this error showing on the page when you try to connect:\\n<pre class=\\\"ckeditor_codeblock\\\">\\nSorry, but we&#39;re having trouble signing you in. We received a bad request.</pre>\\n<br><br><br><br>\\u00a0\"], \"kav_validationstatus\": [\"Reviewed\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka132000000LIYJAA4\"], \"kav_articlenumber__stripped\": [\"1894\"], \"sfversionnumber\": [2], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"coveo_foldingparent\": [\"436e07f628dff691bf6c671839d9dc47e413e0b709d95664c890a84c5b9a\"], \"collection\": [\"default\"], \"sfsourceid\": [\"50032000016t6DPAAY\"], \"date\": [1517399256], \"kav_lastmodifiedby.id\": [\"00532000004vbsoAAA\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type;Product\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00532000004vbsoAAA\"], \"kav_lastmodifiedby.name\": [\"Michael Carter\"], \"kav_articlenumber\": [\"000001894\"], \"permanentid\": [\"dda0aa17bd6148df01cbce21b6c5a9c3d7c095f8dbc88ae34e904f67e365\"]}",
      "sflastmodifiedbyid" : "00532000004vbsoAAA",
      "syssfownerid" : "00532000005Jm9iAAC",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Cannot Connect to Coveo Cloud Platform",
      "rowid" : 5492123,
      "syssfcreatedbyid" : "00532000005Jm9iAAC",
      "sfdescriptionc" : "You have difficulties authenticating on Coveo Cloud Platform after receiving your invite.<br><br>You also have this error showing on the page when you try to connect:\n<pre class=\"ckeditor_codeblock\">\nSorry, but we&#39;re having trouble signing you in. We received a bad request.</pre>\n<br><br><br><br> ",
      "size" : 4249,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1480523106000,
      "sfsourceid" : "50032000016t6DPAAY",
      "clickableuri" : "https://na61.salesforce.com/kA132000000L7ZQ",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00532000005Jm9iAAC",
      "orderingid" : 212384990660370935,
      "sfpublishstatus" : "Online",
      "syssize" : 4249,
      "sysdate" : 1517399256000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Cannot Connect to Coveo Cloud Platform\" uri=\"https://na61.salesforce.com/kA132000000L7ZQ\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "CAD",
      "sfkbid" : "kA132000000L7ZQCA0",
      "sfcausec" : "The Coveo Cloud V2 platform accepts only three authentication provider at the moment:\n<ol><li>Google</li><li>Microsoft Office365</li><li>Salesforce</li></ol>",
      "sfdcexpandedproduct" : "All;All|Cloud Platform;All|Sitecore",
      "syssfcreateddate" : 1480523106000,
      "sflastmodifieddate" : 1480523731000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Michael Carter",
      "collection" : "default",
      "sfdcproduct" : [ "Cloud Platform", "Sitecore" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187515000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Patrick Meunier",
      "sysclickableuri" : "https://na61.salesforce.com/kA132000000L7ZQ",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1479854048000,
      "sfownername" : "Patrick Meunier",
      "sitename" : "Community",
      "sysrowid" : 5492123,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Cannot Connect to Coveo Cloud Platform",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA132000000L7ZQ",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L7ZQCA0/language:en_US",
    "Excerpt" : "You have difficulties authenticating on Coveo Cloud Platform after receiving your invite. ... You also have this error showing on the page when you try to connect: Sorry, but we're having trouble s...",
    "FirstSentences" : null
  }