{
    "title" : "Intermittent \"Coveo encountered an unexpected problem\" error",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA132000000L8br",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
    "excerpt" : "When accessing any Cloud V1 Url, this for example, you are getting \"Coveo encountered an unexpected problem\" error intermittently. ... Looking at in the network tab of your developer tools, you see...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1168,
    "percentScore" : 76.90204,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Intermittent \"Coveo encountered an unexpected problem\" error",
      "sysurihash" : "fYzMdlaAycKCeuIe",
      "urihash" : "fYzMdlaAycKCeuIe",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Intermittent &quot;Coveo encountered an unexpected problem&quot; error\" uri=\"https://na61.salesforce.com/kA132000000L8br\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td colspan=\"1\" rowspan=\"1\"><img alt=\"\" src=\"https://na26.salesforce.com/s.gif\" title=\"\"></img></td><td colspan=\"3\" rowspan=\"1\" id=\"00N32000003NQDK_ilecell\"> </td></tr></tbody></table>\n<br>Please allow a few hours, as our team monitors the cloud activity and will be working on any issue.<br><br>If you are still encountering the issue after a few hours, please contact <a href=\"http://www.coveo.com/en/support/get-help\" target=\"_blank\">Coveo support</a>.",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
      "sflastpublisheddate" : 1486735002000,
      "systransactionid" : 161138,
      "sfurlname" : "2058",
      "sfsystemmodstamp" : 1486735003000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Cloud Platform V1",
      "sysconcepts" : "Coveo ; cloud ; developer tools ; network tab ; unexpected problem ; V1 Url ; clients ; servers ; encountering ; infrastructure ; Resolution ; Environment",
      "sfkbversionnumber" : "2",
      "concepts" : "Coveo ; cloud ; developer tools ; network tab ; unexpected problem ; V1 Url ; clients ; servers ; encountering ; infrastructure ; Resolution ; Environment",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka132000000LM5BAAW",
      "sysindexeddate" : 1518187552000,
      "sfknowledgearticleid" : "kA132000000L8brCAC",
      "sfcreatedbyid" : "00532000005ZlvdAAC",
      "sfconnectorc" : "N/A",
      "permanentid" : "618240cd3659a1d8b7c005a2de771d914fcaa88818b77ee81bf4e71dd606",
      "syslanguage" : [ "English" ],
      "transactionid" : 161138,
      "sfisvisibleinprm" : "true",
      "title" : "Intermittent \"Coveo encountered an unexpected problem\" error",
      "sfversionnumber" : 2,
      "sfarticlenumber" : "000002058",
      "date" : 1486735003000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA132000000L8br\"], \"sflastmodifiedbyname\": [\"Frederic Cote\"], \"kav_coveo_version__c__html_stripped\": [\"Cloud Platform V1\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Cloud Platform\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005ZlvdAAC\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00532000005ZlvdAAC\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Intermittent \\\"Coveo encountered an unexpected problem\\\" error\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005ZlvdAAC\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Intermittent &quot;Coveo encountered an unexpected problem&quot; error\\\" uri=\\\"https://na61.salesforce.com/kA132000000L8br\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Intermittent \\\"Coveo encountered an unexpected problem\\\" error\"], \"kav_isvisibleincsp\": [true], \"hashtmlversion\": [true], \"kav_versionnumber\": [2], \"sfcreatedbyname\": [\"Pierre-Guillaume Laurin\"], \"sflastpublisheddate\": [1486735002], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"Our infrastructure might be encountering some issues that prevent our servers from delivering to clients.\\n \\u00a0 \\u00a0\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1486735002], \"sfsystemmodstamp\": [1486735003], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Cloud Platform\"], \"kav_resolution__c__html_stripped\": [\" \\u00a0 \\n \\n Please allow a few hours, as our team monitors the cloud activity and will be working on any issue. \\n \\n If you are still encountering the issue after a few hours, please contact  Coveo support .\"], \"clickableuri\": [\"https://na61.salesforce.com/kA132000000L8br\"], \"sftitle\": [\"Intermittent \\\"Coveo encountered an unexpected problem\\\" error\"], \"kav_owner.id\": [\"00532000005ZlvdAAC\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA132000000L8brCAC\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"Our infrastructure might be encountering some issues that prevent our servers from delivering to clients.\\n<table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\"><tbody><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\">\\u00a0</td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDK_ilecell\\\">\\u00a0</td></tr></tbody></table>\"], \"sfislatestversion\": [true], \"sfcausec\": [\"Our infrastructure might be encountering some issues that prevent our servers from delivering to clients.\\n<table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\"><tbody><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\">\\u00a0</td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDK_ilecell\\\">\\u00a0</td></tr></tbody></table>\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"2058\"], \"ka_id\": [\"kA132000000L8brCAC\"], \"kav_datacategoryselections.datacategoryname\": [\"Configuration;Cloud_Platform\"], \"coveo_url\": [\"https://na61.salesforce.com/kA132000000L8br\"], \"kav_urlname\": [\"2058\"], \"kav_dc_expanded_product\": [\"All;All|Cloud Platform\"], \"foldingcollection\": [\"99adf56a015af5db5f5bc477783b73036ca64e22b66eedcdc08d3e5206e4\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> <table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\"><tbody><tr><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N60000002ORzP_ilecell\\\">When accessing any Cloud V1 Url, <a href=\\\"https://cloud.coveo.com/#search-alerts/emails/\\\" target=\\\"_blank\\\">this</a><a href=\\\"https://cloud.coveo.com/#search-alerts/emails/\\\" target=\\\"_blank\\\"> for example</a>, you are getting &quot;Coveo encountered an unexpected problem&quot; error intermittently.<br>\\t\\t\\t<br>\\t\\t\\tLooking at in the network tab of your developer\\u00a0tools, you see a 503 - service unavailable error</td></tr><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\">\\u00a0</td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDJ_ilecell\\\">\\u00a0</td></tr><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\">\\u00a0</td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDK_ilecell\\\">\\u00a0</td></tr></tbody></table></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1486735002</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> Our infrastructure might be encountering some issues that prevent our servers from delivering to clients.\\n<table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\"><tbody><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\">\\u00a0</td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDK_ilecell\\\">\\u00a0</td></tr></tbody></table></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> <table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\"><tbody><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\"><img alt=\\\"\\\" src=\\\"https://na26.salesforce.com/s.gif\\\" title=\\\"\\\"></img></td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDK_ilecell\\\">\\u00a0</td></tr></tbody></table>\\n<br>Please allow a few hours, as our team monitors the cloud activity and will be working on any issue.<br><br>If you are still encountering the issue after a few hours, please contact <a href=\\\"http://www.coveo.com/en/support/get-help\\\" target=\\\"_blank\\\">Coveo support</a>.</div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00532000005ZlvdAAC\"], \"kav_description__c__html_stripped\": [\"When accessing any Cloud V1 Url,  this  for example , you are getting \\\"Coveo encountered an unexpected problem\\\" error intermittently. \\n \\t\\t\\t \\n \\t\\t\\tLooking at in the network tab of your developer\\u00a0tools, you see a 503 - service unavailable error \\u00a0 \\u00a0 \\u00a0 \\u00a0\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA132000000L8brCAC\"], \"sfknowledgearticleid\": [\"kA132000000L8brCAC\"], \"sfownername\": [\"Pierre-Guillaume Laurin\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Looking at in the network tab of your developer tools, you see a 503 - service unavailable error\"], \"kav_createddate\": [1486492173], \"language\": [\"English\"], \"coveo_foldingchild\": [\"04e9ab4d4ae963f3894356e908a62110ec2ca5a33af26ca71a5b128622db\"], \"sfownerid\": [\"00532000005ZlvdAAC\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1486735003], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Pierre-Guillaume Laurin\"], \"sfcoveoversionc\": [\"Cloud Platform V1\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"CAD\"], \"sfisdeleted\": [false], \"extractedsize\": [1344], \"size\": [4398], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"<table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\"><tbody><tr><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N60000002ORzP_ilecell\\\">When accessing any Cloud V1 Url, <a href=\\\"https://cloud.coveo.com/#search-alerts/emails/\\\" target=\\\"_blank\\\">this</a><a href=\\\"https://cloud.coveo.com/#search-alerts/emails/\\\" target=\\\"_blank\\\"> for example</a>, you are getting &quot;Coveo encountered an unexpected problem&quot; error intermittently.<br>\\t\\t\\t<br>\\t\\t\\tLooking at in the network tab of your developer\\u00a0tools, you see a 503 - service unavailable error</td></tr><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\">\\u00a0</td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDJ_ilecell\\\">\\u00a0</td></tr><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\">\\u00a0</td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDK_ilecell\\\">\\u00a0</td></tr></tbody></table>\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1486735002], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka132000000LM5BAAW\"], \"kav_currencyisocode\": [\"CAD\"], \"foldingparent\": [\"04e9ab4d4ae963f3894356e908a62110ec2ca5a33af26ca71a5b128622db\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"500320000195KNHAA2\"], \"sfkbversionnumber\": [2], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"<table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\"><tbody><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\"><img alt=\\\"\\\" src=\\\"https://na26.salesforce.com/s.gif\\\" title=\\\"\\\"></img></td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDK_ilecell\\\">\\u00a0</td></tr></tbody></table>\\n<br>Please allow a few hours, as our team monitors the cloud activity and will be working on any issue.<br><br>If you are still encountering the issue after a few hours, please contact <a href=\\\"http://www.coveo.com/en/support/get-help\\\" target=\\\"_blank\\\">Coveo support</a>.\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000q12IAAQ;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000q12JAAQ\"], \"kav_id\": [\"ka132000000LM5BAAW\"], \"sfresolutionc\": [\"<table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\"><tbody><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\"><img alt=\\\"\\\" src=\\\"https://na26.salesforce.com/s.gif\\\" title=\\\"\\\"></img></td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDK_ilecell\\\">\\u00a0</td></tr></tbody></table>\\n<br>Please allow a few hours, as our team monitors the cloud activity and will be working on any issue.<br><br>If you are still encountering the issue after a few hours, please contact <a href=\\\"http://www.coveo.com/en/support/get-help\\\" target=\\\"_blank\\\">Coveo support</a>.\"], \"foldingchild\": [\"04e9ab4d4ae963f3894356e908a62110ec2ca5a33af26ca71a5b128622db\"], \"sfcreateddate\": [1486492173], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1486735003], \"kav_summary__html_stripped\": [\"\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Cloud Platform\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2\"], \"concepts\": [\"Coveo ; cloud ; developer tools ; network tab ; unexpected problem ; V1 Url ; clients ; servers ; encountering ; infrastructure ; Resolution ; Environment\"], \"sfkbid\": [\"kA132000000L8brCAC\"], \"kav_firstpublisheddate\": [1486492110], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"99adf56a015af5db5f5bc477783b73036ca64e22b66eedcdc08d3e5206e4\"], \"sffirstpublisheddate\": [1486492110], \"sflastmodifieddate\": [1486735002], \"kav_coveo_version__c\": [\"Cloud Platform V1\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000003q7JgAAI\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Pierre-Guillaume Laurin\"], \"sfarticlenumber\": [\"000002058\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o32000000q12IAAQ;02o32000000q12JAAQ\"], \"kav_description__c\": [\"<table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\"><tbody><tr><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N60000002ORzP_ilecell\\\">When accessing any Cloud V1 Url, <a href=\\\"https://cloud.coveo.com/#search-alerts/emails/\\\" target=\\\"_blank\\\">this</a><a href=\\\"https://cloud.coveo.com/#search-alerts/emails/\\\" target=\\\"_blank\\\"> for example</a>, you are getting &quot;Coveo encountered an unexpected problem&quot; error intermittently.<br>\\t\\t\\t<br>\\t\\t\\tLooking at in the network tab of your developer\\u00a0tools, you see a 503 - service unavailable error</td></tr><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\">\\u00a0</td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDJ_ilecell\\\">\\u00a0</td></tr><tr><td colspan=\\\"1\\\" rowspan=\\\"1\\\">\\u00a0</td><td colspan=\\\"3\\\" rowspan=\\\"1\\\" id=\\\"00N32000003NQDK_ilecell\\\">\\u00a0</td></tr></tbody></table>\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka132000000LM5BAAW\"], \"kav_articlenumber__stripped\": [\"2058\"], \"sfversionnumber\": [2], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_validationstatus\": [\"Reviewed\"], \"coveo_foldingparent\": [\"04e9ab4d4ae963f3894356e908a62110ec2ca5a33af26ca71a5b128622db\"], \"collection\": [\"default\"], \"sfsourceid\": [\"500320000195KNHAA2\"], \"date\": [1486735003], \"kav_lastmodifiedby.id\": [\"00560000003q7JgAAI\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Article_Type;Product\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000003q7JgAAI\"], \"kav_lastmodifiedby.name\": [\"Frederic Cote\"], \"kav_articlenumber\": [\"000002058\"], \"permanentid\": [\"618240cd3659a1d8b7c005a2de771d914fcaa88818b77ee81bf4e71dd606\"]}",
      "sflastmodifiedbyid" : "00560000003q7JgAAI",
      "syssfownerid" : "00532000005ZlvdAAC",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Intermittent \"Coveo encountered an unexpected problem\" error",
      "rowid" : 5492593,
      "syssfcreatedbyid" : "00532000005ZlvdAAC",
      "sfdescriptionc" : "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td colspan=\"3\" rowspan=\"1\" id=\"00N60000002ORzP_ilecell\">When accessing any Cloud V1 Url, <a href=\"https://cloud.coveo.com/#search-alerts/emails/\" target=\"_blank\">this</a><a href=\"https://cloud.coveo.com/#search-alerts/emails/\" target=\"_blank\"> for example</a>, you are getting &quot;Coveo encountered an unexpected problem&quot; error intermittently.<br>\t\t\t<br>\t\t\tLooking at in the network tab of your developer tools, you see a 503 - service unavailable error</td></tr><tr><td colspan=\"1\" rowspan=\"1\"> </td><td colspan=\"3\" rowspan=\"1\" id=\"00N32000003NQDJ_ilecell\"> </td></tr><tr><td colspan=\"1\" rowspan=\"1\"> </td><td colspan=\"3\" rowspan=\"1\" id=\"00N32000003NQDK_ilecell\"> </td></tr></tbody></table>",
      "size" : 4398,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1486492173000,
      "sfsourceid" : "500320000195KNHAA2",
      "clickableuri" : "https://na61.salesforce.com/kA132000000L8br",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00532000005ZlvdAAC",
      "orderingid" : 212384990660371355,
      "sfpublishstatus" : "Online",
      "syssize" : 4398,
      "sysdate" : 1486735003000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Intermittent &quot;Coveo encountered an unexpected problem&quot; error\" uri=\"https://na61.salesforce.com/kA132000000L8br\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "CAD",
      "sfkbid" : "kA132000000L8brCAC",
      "sfcausec" : "Our infrastructure might be encountering some issues that prevent our servers from delivering to clients.\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td colspan=\"1\" rowspan=\"1\"> </td><td colspan=\"3\" rowspan=\"1\" id=\"00N32000003NQDK_ilecell\"> </td></tr></tbody></table>",
      "sfdcexpandedproduct" : "All;All|Cloud Platform",
      "syssfcreateddate" : 1486492173000,
      "sflastmodifieddate" : 1486735002000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Frederic Cote",
      "collection" : "default",
      "sfdcproduct" : [ "Cloud Platform" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187552000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Pierre-Guillaume Laurin",
      "sysclickableuri" : "https://na61.salesforce.com/kA132000000L8br",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1486492110000,
      "sfownername" : "Pierre-Guillaume Laurin",
      "sitename" : "Community",
      "sysrowid" : 5492593,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Intermittent \"Coveo encountered an unexpected problem\" error",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA132000000L8br",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L8brCAC/language:en_US",
    "Excerpt" : "When accessing any Cloud V1 Url, this for example, you are getting \"Coveo encountered an unexpected problem\" error intermittently. ... Looking at in the network tab of your developer tools, you see...",
    "FirstSentences" : null
  }