{
    "title" : "IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA10d0000004MiK",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
    "excerpt" : "In a cloud index environment, the following error message is reported in Sitecore logs, explaining the App pool recycle triggered by Coveo for Sitecore: ... Cause ... During a reindex, Coveo for Si...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1446,
    "percentScore" : 85.56588,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content",
      "sysurihash" : "vDN2czqd8Hx6D3qe",
      "urihash" : "vDN2czqd8Hx6D3qe",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content\" uri=\"https://na61.salesforce.com/kA10d0000004MiK\" /></parents>",
      "sfdcarticletype" : "Problem/Fix;Product Issue",
      "sfresolutionc" : "This issue has been fixed in the January 2017 (4.0.895) release of Coveo for Sitecore. See the <a href=\"https://developers.coveo.com/display/public/SitecoreV4/Release+Notes+for+January+2017+-+4.0.895\" target=\"_blank\">release notes</a> for this build.<br><br>It is possible to work around the issue by changing the batch size to 1, which prevents timeouts and thus the unhandled &#39;partially filled batch&#39; exception. To do so, you have set the following setting in the Coveo.SearchProvider.Custom.config file:<br> \n<pre class=\"ckeditor_codeblock\">\n&lt;configuration&gt;/&lt;sitecore&gt;/&lt;settings&gt;/&lt;setting name=&quot;Coveo.Indexing.AddDocumentBatchSize&quot; value=&quot;1&quot; /&gt;</pre>\n<br>Do not forget to revert this change once Coveo for Sitecore has been upgraded to a fixed version as this does have a negative impact on rebuild times and resource usage.",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
      "sflastpublisheddate" : 1513634388000,
      "systransactionid" : 161139,
      "sfurlname" : "2816",
      "sfsystemmodstamp" : 1518090402000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Sitecore",
      "sysconcepts" : "App pool ; Coveo ; Sitecore ; cloud ; filled batch ; release ; exception ; resource usage ; negative impact ; config file ; successfully completing ; second delay ; error message ; index environment ; SearchProvider ; Resolution",
      "sfkbversionnumber" : "1",
      "concepts" : "App pool ; Coveo ; Sitecore ; cloud ; filled batch ; release ; exception ; resource usage ; negative impact ; config file ; successfully completing ; second delay ; error message ; index environment ; SearchProvider ; Resolution",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka10d0000004TNwAAM",
      "sysindexeddate" : 1518187597000,
      "sfknowledgearticleid" : "kA10d0000004MiKCAU",
      "sfcreatedbyid" : "00532000006JfuHAAS",
      "sfconnectorc" : "N/A",
      "permanentid" : "cc658ad9d0d86024fc6673b39f4dd300886dd96c0192102befa82a4f9f0f",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content",
      "sfversionnumber" : 1,
      "sfarticlenumber" : "000002816",
      "date" : 1518090402000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA10d0000004MiK\"], \"sflastmodifiedbyname\": [\"Karel Mpungi\"], \"kav_coveo_version__c__html_stripped\": [\"Sitecore\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Sitecore\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000006JfuHAAS\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00532000006JfuHAAS\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000006JfuHAAS\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content\\\" uri=\\\"https://na61.salesforce.com/kA10d0000004MiK\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content\"], \"kav_isvisibleincsp\": [true], \"hashtmlversion\": [true], \"kav_versionnumber\": [1], \"sfcreatedbyname\": [\"Gabriel Beaudoin\"], \"sflastpublisheddate\": [1513634388], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"During a reindex, Coveo for Sitecore batches are sent to the cloud when filled with 10 add or 100 delete operations, or at the end of a 10 second delay when the fill count isn't reached. In the latter case, the thread that triggers the batch dispatch does not handle the 'partially filled batch' exception correctly. This results in an App pool recycle and can prevent the rebuild from successfully completing.\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1513634388], \"sfsystemmodstamp\": [1518090402], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Sitecore\"], \"kav_resolution__c__html_stripped\": [\"This issue has been fixed in the January 2017 (4.0.895) release of Coveo for Sitecore. See the  release notes  for this build. \\n \\n It is possible to work around the issue by changing the batch size to 1, which prevents timeouts and thus the unhandled 'partially filled batch' exception. To do so, you have set the following setting in the Coveo.SearchProvider.Custom.config file: \\n \\u00a0\\n \\n<configuration>/<sitecore>/<settings>/<setting name=\\\"Coveo.Indexing.AddDocumentBatchSize\\\" value=\\\"1\\\" /> \\n \\n Do not forget to revert this change once Coveo for Sitecore has been upgraded to a fixed version as this does have a negative impact on rebuild times and resource usage.\"], \"clickableuri\": [\"https://na61.salesforce.com/kA10d0000004MiK\"], \"sftitle\": [\"IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content\"], \"kav_owner.id\": [\"00532000006JfuHAAS\"], \"sfbuildc\": [\"4.0.780 and earlier\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA10d0000004MiKCAU\"], \"sfdcarticletype\": [\"Problem/Fix;Product Issue\"], \"kav_cause__c\": [\"During a reindex, Coveo for Sitecore batches are sent to the cloud when filled with 10 add or 100 delete operations, or at the end of a 10 second delay when the fill count isn&#39;t reached. In the latter case, the thread that triggers the batch dispatch does not handle the &#39;partially filled batch&#39; exception correctly. This results in an App pool recycle and can prevent the rebuild from successfully completing.\"], \"sfislatestversion\": [true], \"sfcausec\": [\"During a reindex, Coveo for Sitecore batches are sent to the cloud when filled with 10 add or 100 delete operations, or at the end of a 10 second delay when the fill count isn&#39;t reached. In the latter case, the thread that triggers the batch dispatch does not handle the &#39;partially filled batch&#39; exception correctly. This results in an App pool recycle and can prevent the rebuild from successfully completing.\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"2816\"], \"ka_id\": [\"kA10d0000004MiKCAU\"], \"kav_datacategoryselections.datacategoryname\": [\"Sitecore;Product_Issue;Configuration\"], \"coveo_url\": [\"https://na61.salesforce.com/kA10d0000004MiK\"], \"kav_urlname\": [\"2816\"], \"kav_dc_expanded_product\": [\"All;All|Sitecore\"], \"foldingcollection\": [\"e943da58455f3405332488c9520c283e0c38a87965d1677b7155b3fdc0d8\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> In a cloud index environment, the following error message is reported in Sitecore logs, explaining the App pool recycle triggered by Coveo for Sitecore:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nThe ASP.NET worker process will be terminated. Message: Failed to obtain resource located at &#39;https://s3.amazonaws.com/coveo-nprod-customerdata/proda/blobstore/**OrgID**/e0dcb3e4-**EDITED**-bb3dc9d3e0d1?x-amz-security-token=**Edited**\\n\\nNested Exception\\n\\nMessage: The operation has timed out \\n</pre>\\n<br>\\u00a0</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1513634388</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td>4.0.780 and earlier</td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> During a reindex, Coveo for Sitecore batches are sent to the cloud when filled with 10 add or 100 delete operations, or at the end of a 10 second delay when the fill count isn&#39;t reached. In the latter case, the thread that triggers the batch dispatch does not handle the &#39;partially filled batch&#39; exception correctly. This results in an App pool recycle and can prevent the rebuild from successfully completing.</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> This issue has been fixed in the January 2017 (4.0.895) release of Coveo for Sitecore. See the <a href=\\\"https://developers.coveo.com/display/public/SitecoreV4/Release+Notes+for+January+2017+-+4.0.895\\\" target=\\\"_blank\\\">release notes</a> for this build.<br><br>It is possible to work around the issue by changing the batch size to 1, which prevents timeouts and thus the unhandled &#39;partially filled batch&#39; exception. To do so, you have set the following setting in the Coveo.SearchProvider.Custom.config file:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\n&lt;configuration&gt;/&lt;sitecore&gt;/&lt;settings&gt;/&lt;setting name=&quot;Coveo.Indexing.AddDocumentBatchSize&quot; value=&quot;1&quot; /&gt;</pre>\\n<br>Do not forget to revert this change once Coveo for Sitecore has been upgraded to a fixed version as this does have a negative impact on rebuild times and resource usage.</div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00532000006JfuHAAS\"], \"kav_description__c__html_stripped\": [\"In a cloud index environment, the following error message is reported in Sitecore logs, explaining the App pool recycle triggered by Coveo for Sitecore: \\n \\u00a0\\n \\nThe ASP.NET worker process will be terminated. Message: Failed to obtain resource located at 'https://s3.amazonaws.com/coveo-nprod-customerdata/proda/blobstore/**OrgID**/e0dcb3e4-**EDITED**-bb3dc9d3e0d1?x-amz-security-token=**Edited**\\n\\nNested Exception\\n\\nMessage: The operation has timed out \\n \\n \\n \\u00a0\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA10d0000004MiKCAU\"], \"sfknowledgearticleid\": [\"kA10d0000004MiKCAU\"], \"sfownername\": [\"Gabriel Beaudoin\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1511441185], \"kav_build__c\": [\"4.0.780 and earlier\"], \"language\": [\"English\"], \"coveo_foldingchild\": [\"f69140ff20b1111306bee6737ffc8d9b77417042869ea5e738406f32189b\"], \"sfownerid\": [\"00532000006JfuHAAS\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1518090402], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Gabriel Beaudoin\"], \"sfcoveoversionc\": [\"Sitecore\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix;All|Product Issue\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"CAD\"], \"sfisdeleted\": [false], \"extractedsize\": [3348], \"size\": [5872], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"In a cloud index environment, the following error message is reported in Sitecore logs, explaining the App pool recycle triggered by Coveo for Sitecore:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nThe ASP.NET worker process will be terminated. Message: Failed to obtain resource located at &#39;https://s3.amazonaws.com/coveo-nprod-customerdata/proda/blobstore/**OrgID**/e0dcb3e4-**EDITED**-bb3dc9d3e0d1?x-amz-security-token=**Edited**\\n\\nNested Exception\\n\\nMessage: The operation has timed out \\n</pre>\\n<br>\\u00a0\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1513634388], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka10d0000004TNwAAM\"], \"kav_currencyisocode\": [\"CAD\"], \"foldingparent\": [\"f69140ff20b1111306bee6737ffc8d9b77417042869ea5e738406f32189b\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"5000d00001FpMKnAAN\"], \"sfkbversionnumber\": [1], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"This issue has been fixed in the January 2017 (4.0.895) release of Coveo for Sitecore. See the <a href=\\\"https://developers.coveo.com/display/public/SitecoreV4/Release+Notes+for+January+2017+-+4.0.895\\\" target=\\\"_blank\\\">release notes</a> for this build.<br><br>It is possible to work around the issue by changing the batch size to 1, which prevents timeouts and thus the unhandled &#39;partially filled batch&#39; exception. To do so, you have set the following setting in the Coveo.SearchProvider.Custom.config file:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\n&lt;configuration&gt;/&lt;sitecore&gt;/&lt;settings&gt;/&lt;setting name=&quot;Coveo.Indexing.AddDocumentBatchSize&quot; value=&quot;1&quot; /&gt;</pre>\\n<br>Do not forget to revert this change once Coveo for Sitecore has been upgraded to a fixed version as this does have a negative impact on rebuild times and resource usage.\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m7IXAAY;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m7ITAAY;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m9EJAAY\"], \"kav_id\": [\"ka10d0000004TNwAAM\"], \"sfresolutionc\": [\"This issue has been fixed in the January 2017 (4.0.895) release of Coveo for Sitecore. See the <a href=\\\"https://developers.coveo.com/display/public/SitecoreV4/Release+Notes+for+January+2017+-+4.0.895\\\" target=\\\"_blank\\\">release notes</a> for this build.<br><br>It is possible to work around the issue by changing the batch size to 1, which prevents timeouts and thus the unhandled &#39;partially filled batch&#39; exception. To do so, you have set the following setting in the Coveo.SearchProvider.Custom.config file:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\n&lt;configuration&gt;/&lt;sitecore&gt;/&lt;settings&gt;/&lt;setting name=&quot;Coveo.Indexing.AddDocumentBatchSize&quot; value=&quot;1&quot; /&gt;</pre>\\n<br>Do not forget to revert this change once Coveo for Sitecore has been upgraded to a fixed version as this does have a negative impact on rebuild times and resource usage.\"], \"foldingchild\": [\"f69140ff20b1111306bee6737ffc8d9b77417042869ea5e738406f32189b\"], \"sfcreateddate\": [1511441185], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1518090402], \"kav_summary__html_stripped\": [\"\"], \"kav_dc_article_type\": [\"Problem/Fix;Product Issue\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Sitecore\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix;All|Product Issue\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2;2\"], \"concepts\": [\"App pool ; Coveo ; Sitecore ; cloud ; filled batch ; release ; exception ; resource usage ; negative impact ; config file ; successfully completing ; second delay ; error message ; index environment ; SearchProvider ; Resolution\"], \"sfkbid\": [\"kA10d0000004MiKCAU\"], \"kav_firstpublisheddate\": [1513634388], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"e943da58455f3405332488c9520c283e0c38a87965d1677b7155b3fdc0d8\"], \"sffirstpublisheddate\": [1513634388], \"sflastmodifieddate\": [1513634388], \"kav_coveo_version__c\": [\"Sitecore\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Gabriel Beaudoin\"], \"sfarticlenumber\": [\"000002816\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o0d000000m7IXAAY;02o0d000000m7ITAAY;02o0d000000m9EJAAY\"], \"kav_description__c\": [\"In a cloud index environment, the following error message is reported in Sitecore logs, explaining the App pool recycle triggered by Coveo for Sitecore:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nThe ASP.NET worker process will be terminated. Message: Failed to obtain resource located at &#39;https://s3.amazonaws.com/coveo-nprod-customerdata/proda/blobstore/**OrgID**/e0dcb3e4-**EDITED**-bb3dc9d3e0d1?x-amz-security-token=**Edited**\\n\\nNested Exception\\n\\nMessage: The operation has timed out \\n</pre>\\n<br>\\u00a0\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka10d0000004TNwAAM\"], \"kav_articlenumber__stripped\": [\"2816\"], \"sfversionnumber\": [1], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_validationstatus\": [\"Reviewed\"], \"coveo_foldingparent\": [\"f69140ff20b1111306bee6737ffc8d9b77417042869ea5e738406f32189b\"], \"collection\": [\"default\"], \"sfsourceid\": [\"5000d00001FpMKnAAN\"], \"date\": [1518090402], \"kav_lastmodifiedby.id\": [\"00560000002MKBSAA4\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000002MKBSAA4\"], \"kav_lastmodifiedby.name\": [\"Karel Mpungi\"], \"kav_articlenumber\": [\"000002816\"], \"permanentid\": [\"cc658ad9d0d86024fc6673b39f4dd300886dd96c0192102befa82a4f9f0f\"]}",
      "sfbuildc" : "4.0.780 and earlier",
      "sflastmodifiedbyid" : "00560000002MKBSAA4",
      "syssfownerid" : "00532000006JfuHAAS",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content",
      "rowid" : 5493295,
      "syssfcreatedbyid" : "00532000006JfuHAAS",
      "sfdescriptionc" : "In a cloud index environment, the following error message is reported in Sitecore logs, explaining the App pool recycle triggered by Coveo for Sitecore:<br> \n<pre class=\"ckeditor_codeblock\">\nThe ASP.NET worker process will be terminated. Message: Failed to obtain resource located at &#39;https://s3.amazonaws.com/coveo-nprod-customerdata/proda/blobstore/**OrgID**/e0dcb3e4-**EDITED**-bb3dc9d3e0d1?x-amz-security-token=**Edited**\n\nNested Exception\n\nMessage: The operation has timed out \n</pre>\n<br> ",
      "size" : 5872,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1511441185000,
      "sfsourceid" : "5000d00001FpMKnAAN",
      "clickableuri" : "https://na61.salesforce.com/kA10d0000004MiK",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00532000006JfuHAAS",
      "orderingid" : 212384990660372098,
      "sfpublishstatus" : "Online",
      "syssize" : 5872,
      "sysdate" : 1518090402000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content\" uri=\"https://na61.salesforce.com/kA10d0000004MiK\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix;All|Product Issue",
      "sfcurrencyisocode" : "CAD",
      "sfkbid" : "kA10d0000004MiKCAU",
      "sfcausec" : "During a reindex, Coveo for Sitecore batches are sent to the cloud when filled with 10 add or 100 delete operations, or at the end of a 10 second delay when the fill count isn&#39;t reached. In the latter case, the thread that triggers the batch dispatch does not handle the &#39;partially filled batch&#39; exception correctly. This results in an App pool recycle and can prevent the rebuild from successfully completing.",
      "sfdcexpandedproduct" : "All;All|Sitecore",
      "syssfcreateddate" : 1511441185000,
      "sflastmodifieddate" : 1513634388000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Karel Mpungi",
      "collection" : "default",
      "sfdcproduct" : [ "Sitecore" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187597000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Gabriel Beaudoin",
      "sysclickableuri" : "https://na61.salesforce.com/kA10d0000004MiK",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1513634388000,
      "sfownername" : "Gabriel Beaudoin",
      "sitename" : "Community",
      "sysrowid" : 5493295,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "IIS App pool recycles after an unhandled exception in Coveo for Sitecore while reindexing content",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA10d0000004MiK",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MiKCAU/language:en_US",
    "Excerpt" : "In a cloud index environment, the following error message is reported in Sitecore logs, explaining the App pool recycle triggered by Coveo for Sitecore: ... Cause ... During a reindex, Coveo for Si...",
    "FirstSentences" : null
  }