{
    "title" : "Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: \"NameResolutionFailure\". -> The remote name could not be resolved",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA10d0000004N3h",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
    "excerpt" : "This KB explains the root cause and provide a solution to the error below: ... COMMUNICATION ISSUE ... Error description ... The SharePoint server is temporarily not responding or unreachable. ... ...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1382,
    "percentScore" : 83.65087,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: \"NameResolutionFailure\". -> The remote name could not be resolved",
      "sysurihash" : "Lj6F1EesgcfYOyeS",
      "urihash" : "Lj6F1EesgcfYOyeS",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. -&gt; The remote name could not be resolved\" uri=\"https://na61.salesforce.com/kA10d0000004N3h\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "<ul><li>Go into SharePoint Central Administration &gt; Configure alternate access mappings</li></ul>\n\n<p>If your Sitecollection doesn&#39;t appear, click on the &quot;Alternate Access Mapping Collection&quot; dropdown menu on the right top corner, and select &quot;Show All&quot;</p>\n\n<ul><li>Click on the link you want to change</li><li>Type the full URL into the &quot;URL protocol, host and port&quot; field.</li><li>Click OK</li><li>Perform an <a href=\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/resetting_iis.htm\" target=\"_blank\">IIS Reset</a></li></ul>\n\n<p>The source URL should be the Sitecollection full URL</p>\n\n<p><img alt=\"User-added image\" height=\"212\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025EH\" width=\"500\"></img></p>\n\n<p>In the JSON of the source,make sure that the authentication type is NOT set to &quot;SpOnlineNative&quot;</p>\n\n<p><img alt=\"User-added image\" height=\"237\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025EM\" width=\"500\"></img></p>\n\n<p>Rebuild the source</p>\n\n<p><img alt=\"User-added image\" height=\"29\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025ER\" width=\"500\"></img></p>",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
      "sflastpublisheddate" : 1516827589000,
      "systransactionid" : 161139,
      "sfurlname" : "2956",
      "sfsystemmodstamp" : 1517312811000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Cloud Platform\nCoveo On-Premises Crawling Module (Beta)",
      "sysconcepts" : "server ; cause ; authentication type ; JSON of the source ; SpOnlineNative ; port ; host ; kmsp2k10 ; screenshots ; Troubleshooting",
      "sfkbversionnumber" : "1",
      "concepts" : "server ; cause ; authentication type ; JSON of the source ; SpOnlineNative ; port ; host ; kmsp2k10 ; screenshots ; Troubleshooting",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka10d0000004Uk3AAE",
      "sysindexeddate" : 1518187600000,
      "sfknowledgearticleid" : "kA10d0000004N3hCAE",
      "sfcreatedbyid" : "00560000002MKBSAA4",
      "sfconnectorc" : "N/A",
      "permanentid" : "ace0acf19a9766c5618d32cc4dd98cd98f6c0303d5ba6d165658b748425c",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: \"NameResolutionFailure\". -> The remote name could not be resolved",
      "sfversionnumber" : 1,
      "sfarticlenumber" : "000002956",
      "date" : 1517312811000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA10d0000004N3h\"], \"sflastmodifiedbyname\": [\"Karel Mpungi\"], \"kav_coveo_version__c__html_stripped\": [\"Cloud Platform\\r\\nCoveo On-Premises Crawling Module (Beta)\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Cloud Platform\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00560000002MKBSAA4\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: \\\"NameResolutionFailure\\\". -> The remote name could not be resolved\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. -&gt; The remote name could not be resolved\\\" uri=\\\"https://na61.salesforce.com/kA10d0000004N3h\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: \\\"NameResolutionFailure\\\". -> The remote name could not be resolved\"], \"kav_isvisibleincsp\": [true], \"hashtmlversion\": [true], \"kav_versionnumber\": [1], \"sfcreatedbyname\": [\"Karel Mpungi\"], \"sflastpublisheddate\": [1516827589], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"Your site collection URL doesn't contain the full computer name URL. \\n \\n As you see in below screenshots, the Sitecollection URL is \\\"http://vm-sp-kmsp2k10/\\\". It\\u00a0 should be \\\"http://vm-SP-KmSP2K10.sup.coveo.com/\\\" \\n \\u00a0 \\n  \\n \\n \"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1516827589], \"sfsystemmodstamp\": [1517312811], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Cloud Platform\"], \"kav_resolution__c__html_stripped\": [\"Go into SharePoint Central Administration > Configure alternate access mappings \\n\\n If your Sitecollection doesn't appear, click on the \\\"Alternate Access Mapping Collection\\\" dropdown menu on the right top corner, and select \\\"Show All\\\"\\n \\n\\n Click on the link you want to change Type the full URL into the \\\"URL protocol, host and port\\\" field. Click OK Perform an\\u00a0 IIS Reset \\n\\n The source URL should be the Sitecollection full URL\\n \\n\\n \\n \\n\\n In the JSON of the source,make sure that the authentication type is NOT set to \\\"SpOnlineNative\\\"\\n \\n\\n \\n \\n\\n Rebuild the source\\n \\n\\n \\n\"], \"clickableuri\": [\"https://na61.salesforce.com/kA10d0000004N3h\"], \"sftitle\": [\"Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: \\\"NameResolutionFailure\\\". -> The remote name could not be resolved\"], \"kav_owner.id\": [\"00560000002MKBSAA4\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA10d0000004N3hCAE\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"Your site collection URL doesn&#39;t contain the full computer name URL.<br><br>As you see in below screenshots, the Sitecollection URL is &quot;http://vm-sp-kmsp2k10/&quot;. It\\u00a0 should be &quot;http://vm-SP-KmSP2K10.sup.coveo.com/&quot;<br>\\u00a0<br><img alt=\\\"User-added image\\\" height=\\\"169\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000025E7\\\" width=\\\"500\\\"></img><br><br><img alt=\\\"User-added image\\\" height=\\\"280\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000025EC\\\" width=\\\"500\\\"></img>\"], \"sfislatestversion\": [true], \"sfcausec\": [\"Your site collection URL doesn&#39;t contain the full computer name URL.<br><br>As you see in below screenshots, the Sitecollection URL is &quot;http://vm-sp-kmsp2k10/&quot;. It\\u00a0 should be &quot;http://vm-SP-KmSP2K10.sup.coveo.com/&quot;<br>\\u00a0<br><img alt=\\\"User-added image\\\" height=\\\"169\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000025E7\\\" width=\\\"500\\\"></img><br><br><img alt=\\\"User-added image\\\" height=\\\"280\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000025EC\\\" width=\\\"500\\\"></img>\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"2956\"], \"ka_id\": [\"kA10d0000004N3hCAE\"], \"kav_datacategoryselections.datacategoryname\": [\"Cloud_Platform;Configuration\"], \"coveo_url\": [\"https://na61.salesforce.com/kA10d0000004N3h\"], \"kav_urlname\": [\"2956\"], \"kav_dc_expanded_product\": [\"All;All|Cloud Platform\"], \"foldingcollection\": [\"772271fc94c4624f79c7f6a9bd6fd6e242ed0a72ff5902bec613a87b9feb\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> This KB explains the root cause and provide a solution to the error below:<br><br><img alt=\\\"User-added image\\\" height=\\\"99\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy14&amp;refid=0EM0d00000025El\\\" width=\\\"500\\\"></img><br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nCOMMUNICATION ISSUE\\nError description\\nThe SharePoint server is temporarily not responding or unreachable.\\n\\nTroubleshooting\\nIf the problem persists, ensure the Office 365 server is up at http://status.office365.com/.\\nError code\\nSHAREPOINT_UNREACHABLE_SERVER</pre>\\n<br>In Kibana:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\n2018-01-19 11:45:45,795 | WARN  | RefreshThread (Id:13) | Coveo.CES.CustomCrawlers.CustomCrawler | Non fatal exception during refresh.\\nCoveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. -&gt; The remote name could not be resolved: &#39;vm-sp-kmsp2k10&#39; ---&gt; Coveo.Connectors.SharePoint.Exceptions.ConnectionExceptions.UnreachableServerException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. ---&gt; System.Net.WebException: The remote name could not be resolved: &#39;vm-sp-kmsp2k10&#39;\\n   at Coveo.Connectors.Utilities.Parallelism.Tasks.WaitAndThrowOnFailure(Task p_Task)\\n   at Coveo.Connectors.SharePoint.Connection.SharePointConnection.PerformApiCall[T](String p_ServerUrl, Func`1 p_ApiCall)\\n   --- End of inner exception stack trace ---</pre>\\n<br>\\u00a0</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1516827589</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> Your site collection URL doesn&#39;t contain the full computer name URL.<br><br>As you see in below screenshots, the Sitecollection URL is &quot;http://vm-sp-kmsp2k10/&quot;. It\\u00a0 should be &quot;http://vm-SP-KmSP2K10.sup.coveo.com/&quot;<br>\\u00a0<br><img alt=\\\"User-added image\\\" height=\\\"169\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000025E7\\\" width=\\\"500\\\"></img><br><br><img alt=\\\"User-added image\\\" height=\\\"280\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000025EC\\\" width=\\\"500\\\"></img></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> <ul><li>Go into SharePoint Central Administration &gt; Configure alternate access mappings</li></ul>\\n\\n<p>If your Sitecollection doesn&#39;t appear, click on the &quot;Alternate Access Mapping Collection&quot; dropdown menu on the right top corner, and select &quot;Show All&quot;</p>\\n\\n<ul><li>Click on the link you want to change</li><li>Type the full URL into the &quot;URL protocol, host and port&quot; field.</li><li>Click OK</li><li>Perform an\\u00a0<a href=\\\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/resetting_iis.htm\\\" target=\\\"_blank\\\">IIS Reset</a></li></ul>\\n\\n<p>The source URL should be the Sitecollection full URL</p>\\n\\n<p><img alt=\\\"User-added image\\\" height=\\\"212\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025EH\\\" width=\\\"500\\\"></img></p>\\n\\n<p>In the JSON of the source,make sure that the authentication type is NOT set to &quot;SpOnlineNative&quot;</p>\\n\\n<p><img alt=\\\"User-added image\\\" height=\\\"237\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025EM\\\" width=\\\"500\\\"></img></p>\\n\\n<p>Rebuild the source</p>\\n\\n<p><img alt=\\\"User-added image\\\" height=\\\"29\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025ER\\\" width=\\\"500\\\"></img></p></div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00560000002MKBSAA4\"], \"kav_description__c__html_stripped\": [\"This KB explains the root cause and provide a solution to the error below: \\n \\n  \\n \\u00a0\\n \\nCOMMUNICATION ISSUE\\nError description\\nThe SharePoint server is temporarily not responding or unreachable.\\n\\nTroubleshooting\\nIf the problem persists, ensure the Office 365 server is up at http://status.office365.com/.\\nError code\\nSHAREPOINT_UNREACHABLE_SERVER \\n \\n In Kibana: \\n \\u00a0\\n \\n2018-01-19 11:45:45,795 | WARN  | RefreshThread (Id:13) | Coveo.CES.CustomCrawlers.CustomCrawler | Non fatal exception during refresh.\\nCoveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: \\\"NameResolutionFailure\\\". -> The remote name could not be resolved: 'vm-sp-kmsp2k10' ---> Coveo.Connectors.SharePoint.Exceptions.ConnectionExceptions.UnreachableServerException: A web exception occurred on an API call. Web exception status: \\\"NameResolutionFailure\\\". ---> System.Net.WebException: The remote name could not be resolved: 'vm-sp-kmsp2k10'\\n   at Coveo.Connectors.Utilities.Parallelism.Tasks.WaitAndThrowOnFailure(Task p_Task)\\n   at Coveo.Connectors.SharePoint.Connection.SharePointConnection.PerformApiCall[T](String p_ServerUrl, Func`1 p_ApiCall)\\n   --- End of inner exception stack trace --- \\n \\n \\u00a0\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA10d0000004N3hCAE\"], \"sfknowledgearticleid\": [\"kA10d0000004N3hCAE\"], \"sfownername\": [\"Karel Mpungi\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"COMMUNICATION ISSUE\"], \"kav_createddate\": [1516739254], \"language\": [\"English\"], \"coveo_foldingchild\": [\"e6ae0a45d32dd3768c9abc3cf7d0caf2ef77d08974de4eac7e32fb37f385\"], \"sfownerid\": [\"00560000002MKBSAA4\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1517312811], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Karel Mpungi\"], \"sfcoveoversionc\": [\"Cloud Platform\\r\\nCoveo On-Premises Crawling Module (Beta)\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"USD\"], \"sfisdeleted\": [false], \"extractedsize\": [4218], \"size\": [8260], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"This KB explains the root cause and provide a solution to the error below:<br><br><img alt=\\\"User-added image\\\" height=\\\"99\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy14&amp;refid=0EM0d00000025El\\\" width=\\\"500\\\"></img><br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nCOMMUNICATION ISSUE\\nError description\\nThe SharePoint server is temporarily not responding or unreachable.\\n\\nTroubleshooting\\nIf the problem persists, ensure the Office 365 server is up at http://status.office365.com/.\\nError code\\nSHAREPOINT_UNREACHABLE_SERVER</pre>\\n<br>In Kibana:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\n2018-01-19 11:45:45,795 | WARN  | RefreshThread (Id:13) | Coveo.CES.CustomCrawlers.CustomCrawler | Non fatal exception during refresh.\\nCoveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. -&gt; The remote name could not be resolved: &#39;vm-sp-kmsp2k10&#39; ---&gt; Coveo.Connectors.SharePoint.Exceptions.ConnectionExceptions.UnreachableServerException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. ---&gt; System.Net.WebException: The remote name could not be resolved: &#39;vm-sp-kmsp2k10&#39;\\n   at Coveo.Connectors.Utilities.Parallelism.Tasks.WaitAndThrowOnFailure(Task p_Task)\\n   at Coveo.Connectors.SharePoint.Connection.SharePointConnection.PerformApiCall[T](String p_ServerUrl, Func`1 p_ApiCall)\\n   --- End of inner exception stack trace ---</pre>\\n<br>\\u00a0\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1516827589], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka10d0000004Uk3AAE\"], \"kav_currencyisocode\": [\"USD\"], \"foldingparent\": [\"e6ae0a45d32dd3768c9abc3cf7d0caf2ef77d08974de4eac7e32fb37f385\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"5000d00001H8YUIAA3\"], \"sfkbversionnumber\": [1], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"<ul><li>Go into SharePoint Central Administration &gt; Configure alternate access mappings</li></ul>\\n\\n<p>If your Sitecollection doesn&#39;t appear, click on the &quot;Alternate Access Mapping Collection&quot; dropdown menu on the right top corner, and select &quot;Show All&quot;</p>\\n\\n<ul><li>Click on the link you want to change</li><li>Type the full URL into the &quot;URL protocol, host and port&quot; field.</li><li>Click OK</li><li>Perform an\\u00a0<a href=\\\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/resetting_iis.htm\\\" target=\\\"_blank\\\">IIS Reset</a></li></ul>\\n\\n<p>The source URL should be the Sitecollection full URL</p>\\n\\n<p><img alt=\\\"User-added image\\\" height=\\\"212\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025EH\\\" width=\\\"500\\\"></img></p>\\n\\n<p>In the JSON of the source,make sure that the authentication type is NOT set to &quot;SpOnlineNative&quot;</p>\\n\\n<p><img alt=\\\"User-added image\\\" height=\\\"237\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025EM\\\" width=\\\"500\\\"></img></p>\\n\\n<p>Rebuild the source</p>\\n\\n<p><img alt=\\\"User-added image\\\" height=\\\"29\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025ER\\\" width=\\\"500\\\"></img></p>\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000mCYtAAM;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000mCYuAAM\"], \"kav_id\": [\"ka10d0000004Uk3AAE\"], \"sfresolutionc\": [\"<ul><li>Go into SharePoint Central Administration &gt; Configure alternate access mappings</li></ul>\\n\\n<p>If your Sitecollection doesn&#39;t appear, click on the &quot;Alternate Access Mapping Collection&quot; dropdown menu on the right top corner, and select &quot;Show All&quot;</p>\\n\\n<ul><li>Click on the link you want to change</li><li>Type the full URL into the &quot;URL protocol, host and port&quot; field.</li><li>Click OK</li><li>Perform an\\u00a0<a href=\\\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/resetting_iis.htm\\\" target=\\\"_blank\\\">IIS Reset</a></li></ul>\\n\\n<p>The source URL should be the Sitecollection full URL</p>\\n\\n<p><img alt=\\\"User-added image\\\" height=\\\"212\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025EH\\\" width=\\\"500\\\"></img></p>\\n\\n<p>In the JSON of the source,make sure that the authentication type is NOT set to &quot;SpOnlineNative&quot;</p>\\n\\n<p><img alt=\\\"User-added image\\\" height=\\\"237\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025EM\\\" width=\\\"500\\\"></img></p>\\n\\n<p>Rebuild the source</p>\\n\\n<p><img alt=\\\"User-added image\\\" height=\\\"29\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000025ER\\\" width=\\\"500\\\"></img></p>\"], \"foldingchild\": [\"e6ae0a45d32dd3768c9abc3cf7d0caf2ef77d08974de4eac7e32fb37f385\"], \"sfcreateddate\": [1516739254], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1517312811], \"kav_summary__html_stripped\": [\"\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Cloud Platform\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2\"], \"concepts\": [\"server ; cause ; authentication type ; JSON of the source ; SpOnlineNative ; port ; host ; kmsp2k10 ; screenshots ; Troubleshooting\"], \"sfkbid\": [\"kA10d0000004N3hCAE\"], \"kav_firstpublisheddate\": [1516827589], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"772271fc94c4624f79c7f6a9bd6fd6e242ed0a72ff5902bec613a87b9feb\"], \"sffirstpublisheddate\": [1516827589], \"sflastmodifieddate\": [1516827589], \"kav_coveo_version__c\": [\"Cloud Platform\\r\\nCoveo On-Premises Crawling Module (Beta)\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Karel Mpungi\"], \"sfarticlenumber\": [\"000002956\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o0d000000mCYtAAM;02o0d000000mCYuAAM\"], \"kav_description__c\": [\"This KB explains the root cause and provide a solution to the error below:<br><br><img alt=\\\"User-added image\\\" height=\\\"99\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy14&amp;refid=0EM0d00000025El\\\" width=\\\"500\\\"></img><br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nCOMMUNICATION ISSUE\\nError description\\nThe SharePoint server is temporarily not responding or unreachable.\\n\\nTroubleshooting\\nIf the problem persists, ensure the Office 365 server is up at http://status.office365.com/.\\nError code\\nSHAREPOINT_UNREACHABLE_SERVER</pre>\\n<br>In Kibana:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\n2018-01-19 11:45:45,795 | WARN  | RefreshThread (Id:13) | Coveo.CES.CustomCrawlers.CustomCrawler | Non fatal exception during refresh.\\nCoveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. -&gt; The remote name could not be resolved: &#39;vm-sp-kmsp2k10&#39; ---&gt; Coveo.Connectors.SharePoint.Exceptions.ConnectionExceptions.UnreachableServerException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. ---&gt; System.Net.WebException: The remote name could not be resolved: &#39;vm-sp-kmsp2k10&#39;\\n   at Coveo.Connectors.Utilities.Parallelism.Tasks.WaitAndThrowOnFailure(Task p_Task)\\n   at Coveo.Connectors.SharePoint.Connection.SharePointConnection.PerformApiCall[T](String p_ServerUrl, Func`1 p_ApiCall)\\n   --- End of inner exception stack trace ---</pre>\\n<br>\\u00a0\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka10d0000004Uk3AAE\"], \"kav_articlenumber__stripped\": [\"2956\"], \"sfversionnumber\": [1], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_validationstatus\": [\"Reviewed\"], \"coveo_foldingparent\": [\"e6ae0a45d32dd3768c9abc3cf7d0caf2ef77d08974de4eac7e32fb37f385\"], \"collection\": [\"default\"], \"sfsourceid\": [\"5000d00001H8YUIAA3\"], \"date\": [1517312811], \"kav_lastmodifiedby.id\": [\"00560000002MKBSAA4\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000002MKBSAA4\"], \"kav_lastmodifiedby.name\": [\"Karel Mpungi\"], \"kav_articlenumber\": [\"000002956\"], \"permanentid\": [\"ace0acf19a9766c5618d32cc4dd98cd98f6c0303d5ba6d165658b748425c\"]}",
      "sflastmodifiedbyid" : "00560000002MKBSAA4",
      "syssfownerid" : "00560000002MKBSAA4",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: \"NameResolutionFailure\". -> The remote name could not be resolved",
      "rowid" : 5493349,
      "syssfcreatedbyid" : "00560000002MKBSAA4",
      "sfdescriptionc" : "This KB explains the root cause and provide a solution to the error below:<br><br><img alt=\"User-added image\" height=\"99\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy14&amp;refid=0EM0d00000025El\" width=\"500\"></img><br> \n<pre class=\"ckeditor_codeblock\">\nCOMMUNICATION ISSUE\nError description\nThe SharePoint server is temporarily not responding or unreachable.\n\nTroubleshooting\nIf the problem persists, ensure the Office 365 server is up at http://status.office365.com/.\nError code\nSHAREPOINT_UNREACHABLE_SERVER</pre>\n<br>In Kibana:<br> \n<pre class=\"ckeditor_codeblock\">\n2018-01-19 11:45:45,795 | WARN  | RefreshThread (Id:13) | Coveo.CES.CustomCrawlers.CustomCrawler | Non fatal exception during refresh.\nCoveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. -&gt; The remote name could not be resolved: &#39;vm-sp-kmsp2k10&#39; ---&gt; Coveo.Connectors.SharePoint.Exceptions.ConnectionExceptions.UnreachableServerException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. ---&gt; System.Net.WebException: The remote name could not be resolved: &#39;vm-sp-kmsp2k10&#39;\n   at Coveo.Connectors.Utilities.Parallelism.Tasks.WaitAndThrowOnFailure(Task p_Task)\n   at Coveo.Connectors.SharePoint.Connection.SharePointConnection.PerformApiCall[T](String p_ServerUrl, Func`1 p_ApiCall)\n   --- End of inner exception stack trace ---</pre>\n<br> ",
      "size" : 8260,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1516739254000,
      "sfsourceid" : "5000d00001H8YUIAA3",
      "clickableuri" : "https://na61.salesforce.com/kA10d0000004N3h",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00560000002MKBSAA4",
      "orderingid" : 212384990660372157,
      "sfpublishstatus" : "Online",
      "syssize" : 8260,
      "sysdate" : 1517312811000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: &quot;NameResolutionFailure&quot;. -&gt; The remote name could not be resolved\" uri=\"https://na61.salesforce.com/kA10d0000004N3h\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "USD",
      "sfkbid" : "kA10d0000004N3hCAE",
      "sfcausec" : "Your site collection URL doesn&#39;t contain the full computer name URL.<br><br>As you see in below screenshots, the Sitecollection URL is &quot;http://vm-sp-kmsp2k10/&quot;. It  should be &quot;http://vm-SP-KmSP2K10.sup.coveo.com/&quot;<br> <br><img alt=\"User-added image\" height=\"169\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000025E7\" width=\"500\"></img><br><br><img alt=\"User-added image\" height=\"280\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Uk3&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000025EC\" width=\"500\"></img>",
      "sfdcexpandedproduct" : "All;All|Cloud Platform",
      "syssfcreateddate" : 1516739254000,
      "sflastmodifieddate" : 1516827589000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Karel Mpungi",
      "collection" : "default",
      "sfdcproduct" : [ "Cloud Platform" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187600000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Karel Mpungi",
      "sysclickableuri" : "https://na61.salesforce.com/kA10d0000004N3h",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1516827589000,
      "sfownername" : "Karel Mpungi",
      "sitename" : "Community",
      "sysrowid" : 5493349,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Coveo.CES.CustomCrawlers.CrawlerCantStartRefreshException: A web exception occurred on an API call. Web exception status: \"NameResolutionFailure\". -> The remote name could not be resolved",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA10d0000004N3h",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004N3hCAE/language:en_US",
    "Excerpt" : "This KB explains the root cause and provide a solution to the error below: ... COMMUNICATION ISSUE ... Error description ... The SharePoint server is temporarily not responding or unreachable. ... ...",
    "FirstSentences" : null
  }