{
    "title" : "SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA132000000L823",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
    "excerpt" : "You try to rebuild a source in the Cloud Platform and you get an \"Authentication issue\" when hovering on the window, you see the following message ... We are no longer able to authenticate and cons...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1341,
    "percentScore" : 82.40069,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin",
      "sysurihash" : "gPzMPqHypJLYlV5v",
      "urihash" : "gPzMPqHypJLYlV5v",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin\" uri=\"https://na61.salesforce.com/kA132000000L823\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "- Go to your org in the <a href=\"https://cloud.coveo.com/#content/sources \" target=\"_blank\">cloudUI</a> <br><br>- Click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials. <br><br>- Re-login with the appropriate crawling user. <br><br>- You should get a confirmation page requesting that you confirm access to Salesforce for this user. <br><br>- Click Yes. ",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
      "sflastpublisheddate" : 1505498225000,
      "systransactionid" : 161139,
      "sfurlname" : "1970",
      "sfsystemmodstamp" : 1516275942000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Cloud Platform V1",
      "sysconcepts" : "Salesforce ; org ; authentication ; cloudUI ; Cloud Platform ; requesting ; confirmation ; Re-login ; Resolution",
      "sfkbversionnumber" : "5",
      "concepts" : "Salesforce ; org ; authentication ; cloudUI ; Cloud Platform ; requesting ; confirmation ; Re-login ; Resolution",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka10d0000004SN7AAM",
      "sysindexeddate" : 1518187582000,
      "sfknowledgearticleid" : "kA132000000L823CAC",
      "sfcreatedbyid" : "00532000005ZlvdAAC",
      "sfconnectorc" : "N/A",
      "permanentid" : "b3d2add0cdda449789196b12922466a14e4ca61701c7cf86ef328b7d35f2",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin",
      "sfversionnumber" : 5,
      "sfarticlenumber" : "000001970",
      "date" : 1516275942000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA132000000L823\"], \"sflastmodifiedbyname\": [\"Karel Mpungi\"], \"kav_coveo_version__c__html_stripped\": [\"Cloud Platform V1\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Cloud Platform;All|Salesforce\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005ZlvdAAC\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00532000005ZlvdAAC\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005ZlvdAAC\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin\\\" uri=\\\"https://na61.salesforce.com/kA132000000L823\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin\"], \"kav_isvisibleincsp\": [true], \"hashtmlversion\": [true], \"kav_versionnumber\": [5], \"sfcreatedbyname\": [\"Pierre-Guillaume Laurin\"], \"sflastpublisheddate\": [1505498225], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"This issue mostly arise after a Salesforce instance has been refreshed. It is caused by the refresh token in Salesforce org having been reupdated hence the refresh token your Coveo org has in memory for the Salesforce organisation you are trying to crawl is no longer valid.\\u00a0\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1505498225], \"sfsystemmodstamp\": [1516275942], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Cloud Platform;Salesforce\"], \"kav_resolution__c__html_stripped\": [\"- Go to your org in the  cloudUI \\u00a0 \\n \\n - Click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials.\\u00a0 \\n \\n - Re-login with the appropriate crawling user.\\u00a0 \\n \\n - You should get a confirmation page requesting that you confirm access to Salesforce for this user.\\u00a0 \\n \\n - Click Yes.\\u00a0\"], \"clickableuri\": [\"https://na61.salesforce.com/kA132000000L823\"], \"sftitle\": [\"SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin\"], \"kav_owner.id\": [\"00532000005ZlvdAAC\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA132000000L823CAC\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"This issue mostly arise after a Salesforce instance has been refreshed. It is caused by the refresh token in Salesforce org having been reupdated hence the refresh token your Coveo org has in memory for the Salesforce organisation you are trying to crawl is no longer valid.\\u00a0\"], \"sfislatestversion\": [true], \"sfcausec\": [\"This issue mostly arise after a Salesforce instance has been refreshed. It is caused by the refresh token in Salesforce org having been reupdated hence the refresh token your Coveo org has in memory for the Salesforce organisation you are trying to crawl is no longer valid.\\u00a0\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"1970\"], \"ka_id\": [\"kA132000000L823CAC\"], \"kav_datacategoryselections.datacategoryname\": [\"Cloud_Platform;Configuration;Salesforce\"], \"coveo_url\": [\"https://na61.salesforce.com/kA132000000L823\"], \"kav_urlname\": [\"1970\"], \"kav_dc_expanded_product\": [\"All;All|Cloud Platform;All|Salesforce\"], \"foldingcollection\": [\"d833bcd1ab233de42dec586c07e258e8b68fa351eab3fac9129e05029fc8\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> You try to rebuild a source in the Cloud Platform and you get an &quot;Authentication issue&quot; when hovering on the window, you see the following message<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nWe are no longer able to authenticate and consequently cannot refresh your source.\\n\\nEdit the source to refresh your authentication token.\\n\\nAuthentication issue\\n\\nSALESFORCE_UNABLE_TO_AUTHENTICATE\\n</pre></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1505498225</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> This issue mostly arise after a Salesforce instance has been refreshed. It is caused by the refresh token in Salesforce org having been reupdated hence the refresh token your Coveo org has in memory for the Salesforce organisation you are trying to crawl is no longer valid.\\u00a0</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> - Go to your org in the <a href=\\\"https://cloud.coveo.com/#content/sources\\u00a0\\\" target=\\\"_blank\\\">cloudUI</a>\\u00a0<br><br>- Click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials.\\u00a0<br><br>- Re-login with the appropriate crawling user.\\u00a0<br><br>- You should get a confirmation page requesting that you confirm access to Salesforce for this user.\\u00a0<br><br>- Click Yes.\\u00a0</div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00532000005ZlvdAAC\"], \"kav_description__c__html_stripped\": [\"You try to rebuild a source in the Cloud Platform and you get an \\\"Authentication issue\\\" when hovering on the window, you see the following message \\n \\u00a0\\n \\nWe are no longer able to authenticate and consequently cannot refresh your source.\\n\\nEdit the source to refresh your authentication token.\\n\\nAuthentication issue\\n\\nSALESFORCE_UNABLE_TO_AUTHENTICATE\\n\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA132000000L823CAC\"], \"sfknowledgearticleid\": [\"kA132000000L823CAC\"], \"sfownername\": [\"Pierre-Guillaume Laurin\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1505399287], \"language\": [\"English\"], \"coveo_foldingchild\": [\"3132fe645c70968b66d93d8b0e0e79bfc30d1e250c14818245f215601161\"], \"sfownerid\": [\"00532000005ZlvdAAC\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1516275942], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Pierre-Guillaume Laurin\"], \"sfcoveoversionc\": [\"Cloud Platform V1\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"CAD\"], \"sfisdeleted\": [false], \"extractedsize\": [2114], \"size\": [4433], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"You try to rebuild a source in the Cloud Platform and you get an &quot;Authentication issue&quot; when hovering on the window, you see the following message<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nWe are no longer able to authenticate and consequently cannot refresh your source.\\n\\nEdit the source to refresh your authentication token.\\n\\nAuthentication issue\\n\\nSALESFORCE_UNABLE_TO_AUTHENTICATE\\n</pre>\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1505498225], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka10d0000004SN7AAM\"], \"kav_currencyisocode\": [\"CAD\"], \"foldingparent\": [\"3132fe645c70968b66d93d8b0e0e79bfc30d1e250c14818245f215601161\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"50032000017NL6DAAW\"], \"sfkbversionnumber\": [5], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"- Go to your org in the <a href=\\\"https://cloud.coveo.com/#content/sources\\u00a0\\\" target=\\\"_blank\\\">cloudUI</a>\\u00a0<br><br>- Click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials.\\u00a0<br><br>- Re-login with the appropriate crawling user.\\u00a0<br><br>- You should get a confirmation page requesting that you confirm access to Salesforce for this user.\\u00a0<br><br>- Click Yes.\\u00a0\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m2F2AAI;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m2F1AAI;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m2F3AAI\"], \"kav_id\": [\"ka10d0000004SN7AAM\"], \"sfresolutionc\": [\"- Go to your org in the <a href=\\\"https://cloud.coveo.com/#content/sources\\u00a0\\\" target=\\\"_blank\\\">cloudUI</a>\\u00a0<br><br>- Click on the source in the CloudUI to edit it. You will be prompted for Salesforce Credentials.\\u00a0<br><br>- Re-login with the appropriate crawling user.\\u00a0<br><br>- You should get a confirmation page requesting that you confirm access to Salesforce for this user.\\u00a0<br><br>- Click Yes.\\u00a0\"], \"foldingchild\": [\"3132fe645c70968b66d93d8b0e0e79bfc30d1e250c14818245f215601161\"], \"sfcreateddate\": [1505399287], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1516275942], \"kav_summary__html_stripped\": [\"\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Cloud Platform;Salesforce\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2;2\"], \"concepts\": [\"Salesforce ; org ; authentication ; cloudUI ; Cloud Platform ; requesting ; confirmation ; Re-login ; Resolution\"], \"sfkbid\": [\"kA132000000L823CAC\"], \"kav_firstpublisheddate\": [1482426642], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"d833bcd1ab233de42dec586c07e258e8b68fa351eab3fac9129e05029fc8\"], \"sffirstpublisheddate\": [1482426642], \"sflastmodifieddate\": [1505498225], \"kav_coveo_version__c\": [\"Cloud Platform V1\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Pierre-Guillaume Laurin\"], \"sfarticlenumber\": [\"000001970\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o0d000000m2F2AAI;02o0d000000m2F1AAI;02o0d000000m2F3AAI\"], \"kav_description__c\": [\"You try to rebuild a source in the Cloud Platform and you get an &quot;Authentication issue&quot; when hovering on the window, you see the following message<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nWe are no longer able to authenticate and consequently cannot refresh your source.\\n\\nEdit the source to refresh your authentication token.\\n\\nAuthentication issue\\n\\nSALESFORCE_UNABLE_TO_AUTHENTICATE\\n</pre>\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka10d0000004SN7AAM\"], \"kav_articlenumber__stripped\": [\"1970\"], \"sfversionnumber\": [5], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_validationstatus\": [\"Reviewed\"], \"coveo_foldingparent\": [\"3132fe645c70968b66d93d8b0e0e79bfc30d1e250c14818245f215601161\"], \"collection\": [\"default\"], \"sfsourceid\": [\"50032000017NL6DAAW\"], \"date\": [1516275942], \"kav_lastmodifiedby.id\": [\"00560000002MKBSAA4\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type;Product\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000002MKBSAA4\"], \"kav_lastmodifiedby.name\": [\"Karel Mpungi\"], \"kav_articlenumber\": [\"000001970\"], \"permanentid\": [\"b3d2add0cdda449789196b12922466a14e4ca61701c7cf86ef328b7d35f2\"]}",
      "sflastmodifiedbyid" : "00560000002MKBSAA4",
      "syssfownerid" : "00532000005ZlvdAAC",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin",
      "rowid" : 5493058,
      "syssfcreatedbyid" : "00532000005ZlvdAAC",
      "sfdescriptionc" : "You try to rebuild a source in the Cloud Platform and you get an &quot;Authentication issue&quot; when hovering on the window, you see the following message<br> \n<pre class=\"ckeditor_codeblock\">\nWe are no longer able to authenticate and consequently cannot refresh your source.\n\nEdit the source to refresh your authentication token.\n\nAuthentication issue\n\nSALESFORCE_UNABLE_TO_AUTHENTICATE\n</pre>",
      "size" : 4433,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1505399287000,
      "sfsourceid" : "50032000017NL6DAAW",
      "clickableuri" : "https://na61.salesforce.com/kA132000000L823",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00532000005ZlvdAAC",
      "orderingid" : 212384990660371866,
      "sfpublishstatus" : "Online",
      "syssize" : 4433,
      "sysdate" : 1516275942000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin\" uri=\"https://na61.salesforce.com/kA132000000L823\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "CAD",
      "sfkbid" : "kA132000000L823CAC",
      "sfcausec" : "This issue mostly arise after a Salesforce instance has been refreshed. It is caused by the refresh token in Salesforce org having been reupdated hence the refresh token your Coveo org has in memory for the Salesforce organisation you are trying to crawl is no longer valid. ",
      "sfdcexpandedproduct" : "All;All|Cloud Platform;All|Salesforce",
      "syssfcreateddate" : 1505399287000,
      "sflastmodifieddate" : 1505498225000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Karel Mpungi",
      "collection" : "default",
      "sfdcproduct" : [ "Cloud Platform", "Salesforce" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187582000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Pierre-Guillaume Laurin",
      "sysclickableuri" : "https://na61.salesforce.com/kA132000000L823",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1482426642000,
      "sfownername" : "Pierre-Guillaume Laurin",
      "sitename" : "Community",
      "sysrowid" : 5493058,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "SALESFORCE_UNABLE_TO_AUTHENTICATE error in cloud Admin",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA132000000L823",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000L823CAC/language:en_US",
    "Excerpt" : "You try to rebuild a source in the Cloud Platform and you get an \"Authentication issue\" when hovering on the window, you see the following message ... We are no longer able to authenticate and cons...",
    "FirstSentences" : null
  }