{
    "title" : "Unable to refresh a push source: The total number of locks exceeds the lock table size",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA10d0000004Mij",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
    "excerpt" : "You are unable to refresh content of a push source in a Cloud V2 org. ... When running log4nets, you get the following error message: ... Cause ... As the error message points out, this is due to t...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1292,
    "percentScore" : 80.88122,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Unable to refresh a push source: The total number of locks exceeds the lock table size",
      "sysurihash" : "yvfQTj1uf5VgxsZI",
      "urihash" : "yvfQTj1uf5VgxsZI",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Unable to refresh a push source: The total number of locks exceeds the lock table size\" uri=\"https://na61.salesforce.com/kA10d0000004Mij\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "As <a href=\"https://stackoverflow.com/questions/6901108/the-total-number-of-locks-exceeds-the-lock-table-size\" target=\"_blank\">this post</a> shows, increase the innodb_buffer_pool_size variable to 64MB for MySQL server. Here are the steps as per the documentation:\n<ol><li>Locate the file <code>my.cnf</code> from the server. For Linux servers this will be mostly at <code>/etc/my.cnf</code></li><li>Add the line <code>innodb_buffer_pool_size=64MB</code> to this file</li><li>Restart the MySQL server</li></ol>\n\n<p>To restart the MySQL server, you can use anyone of the below 2 options:</p>\n\n<ol><li>service mysqld restart</li><li>/etc/init.d/mysqld restart</li></ol>",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
      "sflastpublisheddate" : 1513629714000,
      "systransactionid" : 161139,
      "sfurlname" : "2820",
      "sfsystemmodstamp" : 1513683920000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Coveo Enterprise Search",
      "sysconcepts" : "MySQL server ; error message ; post shows ; running log4nets ; V2 org ; push source ; documentation ; pool ; Resolution ; lock-table-size",
      "sfkbversionnumber" : "1",
      "concepts" : "MySQL server ; error message ; post shows ; running log4nets ; V2 org ; push source ; documentation ; pool ; Resolution ; lock-table-size",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka10d0000004TOaAAM",
      "sysindexeddate" : 1518187597000,
      "sfknowledgearticleid" : "kA10d0000004MijCAE",
      "sfcreatedbyid" : "00532000005ZlvdAAC",
      "sfconnectorc" : "N/A",
      "permanentid" : "4ad769ada5a24cc2e1eca2648004d18f4e33084931854eae804a83de45fd",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "Unable to refresh a push source: The total number of locks exceeds the lock table size",
      "sfversionnumber" : 1,
      "sfarticlenumber" : "000002820",
      "date" : 1513683920000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA10d0000004Mij\"], \"sflastmodifiedbyname\": [\"Karel Mpungi\"], \"kav_coveo_version__c__html_stripped\": [\"Coveo Enterprise Search\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Coveo Enterprise Search\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005ZlvdAAC\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00532000005ZlvdAAC\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Unable to refresh a push source: The total number of locks exceeds the lock table size\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005ZlvdAAC\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Unable to refresh a push source: The total number of locks exceeds the lock table size\\\" uri=\\\"https://na61.salesforce.com/kA10d0000004Mij\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Unable to refresh a push source: The total number of locks exceeds the lock table size\"], \"kav_isvisibleincsp\": [true], \"hashtmlversion\": [true], \"kav_versionnumber\": [1], \"sfcreatedbyname\": [\"Pierre-Guillaume Laurin\"], \"sflastpublisheddate\": [1513629714], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"As the error message points out, this is due to the\\u00a0 total number of locks exceeds the lock-table-size\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1513629714], \"sfsystemmodstamp\": [1513683920], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Coveo Enterprise Search\"], \"kav_resolution__c__html_stripped\": [\"As  this post \\u00a0shows, increase the innodb_buffer_pool_size variable to 64MB for MySQL server. Here are the steps as per the documentation:\\n Locate the file\\u00a0 my.cnf \\u00a0from the server. For Linux servers this will be mostly at\\u00a0 /etc/my.cnf Add the line\\u00a0 innodb_buffer_pool_size=64MB \\u00a0to this file Restart the MySQL server \\n\\n To restart the MySQL server, you can use anyone of the below 2 options:\\n \\n\\n service mysqld restart /etc/init.d/mysqld restart\"], \"clickableuri\": [\"https://na61.salesforce.com/kA10d0000004Mij\"], \"sftitle\": [\"Unable to refresh a push source: The total number of locks exceeds the lock table size\"], \"kav_owner.id\": [\"00532000005ZlvdAAC\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA10d0000004MijCAE\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"As the error message points out, this is due to the\\u00a0<a href=\\\"https://stackoverflow.com/questions/6901108/the-total-number-of-locks-exceeds-the-lock-table-size\\\" target=\\\"_blank\\\">total number of locks exceeds the lock-table-size</a>\"], \"sfislatestversion\": [true], \"sfcausec\": [\"As the error message points out, this is due to the\\u00a0<a href=\\\"https://stackoverflow.com/questions/6901108/the-total-number-of-locks-exceeds-the-lock-table-size\\\" target=\\\"_blank\\\">total number of locks exceeds the lock-table-size</a>\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"2820\"], \"ka_id\": [\"kA10d0000004MijCAE\"], \"kav_datacategoryselections.datacategoryname\": [\"Coveo_Enterprise_Search;Configuration\"], \"coveo_url\": [\"https://na61.salesforce.com/kA10d0000004Mij\"], \"kav_urlname\": [\"2820\"], \"kav_dc_expanded_product\": [\"All;All|Coveo Enterprise Search\"], \"foldingcollection\": [\"c21e283e0602160acefd4055caf8fbb9293a49f369d0c9b07150724b915e\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> You are unable to refresh content of a push source in a Cloud V2 org. When <a href=\\\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/logging_information_with_log4net.htm\\\" target=\\\"_blank\\\">running log4nets</a>, you get the following error message:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nMySql.Data.MySqlClient.MySqlException (0x80004005): The total number of locks exceeds the lock table size</pre>\\n<br>\\u00a0</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1513629714</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> As the error message points out, this is due to the\\u00a0<a href=\\\"https://stackoverflow.com/questions/6901108/the-total-number-of-locks-exceeds-the-lock-table-size\\\" target=\\\"_blank\\\">total number of locks exceeds the lock-table-size</a></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> As <a href=\\\"https://stackoverflow.com/questions/6901108/the-total-number-of-locks-exceeds-the-lock-table-size\\\" target=\\\"_blank\\\">this post</a>\\u00a0shows, increase the innodb_buffer_pool_size variable to 64MB for MySQL server. Here are the steps as per the documentation:\\n<ol><li>Locate the file\\u00a0<code>my.cnf</code>\\u00a0from the server. For Linux servers this will be mostly at\\u00a0<code>/etc/my.cnf</code></li><li>Add the line\\u00a0<code>innodb_buffer_pool_size=64MB</code>\\u00a0to this file</li><li>Restart the MySQL server</li></ol>\\n\\n<p>To restart the MySQL server, you can use anyone of the below 2 options:</p>\\n\\n<ol><li>service mysqld restart</li><li>/etc/init.d/mysqld restart</li></ol></div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00532000005ZlvdAAC\"], \"kav_description__c__html_stripped\": [\"You are unable to refresh content of a push source in a Cloud V2 org. When  running log4nets , you get the following error message: \\n \\u00a0\\n \\nMySql.Data.MySqlClient.MySqlException (0x80004005): The total number of locks exceeds the lock table size \\n \\n \\u00a0\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA10d0000004MijCAE\"], \"sfknowledgearticleid\": [\"kA10d0000004MijCAE\"], \"sfownername\": [\"Pierre-Guillaume Laurin\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1511531908], \"language\": [\"English\"], \"coveo_foldingchild\": [\"c18ed3d36f5b0f830c015355ba1aea47bda50f78d96f56647e4c178276aa\"], \"sfownerid\": [\"00532000005ZlvdAAC\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1513683920], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Pierre-Guillaume Laurin\"], \"sfcoveoversionc\": [\"Coveo Enterprise Search\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"CAD\"], \"sfisdeleted\": [false], \"extractedsize\": [1874], \"size\": [4482], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"You are unable to refresh content of a push source in a Cloud V2 org. When <a href=\\\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/logging_information_with_log4net.htm\\\" target=\\\"_blank\\\">running log4nets</a>, you get the following error message:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nMySql.Data.MySqlClient.MySqlException (0x80004005): The total number of locks exceeds the lock table size</pre>\\n<br>\\u00a0\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1513629714], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka10d0000004TOaAAM\"], \"kav_currencyisocode\": [\"CAD\"], \"foldingparent\": [\"c18ed3d36f5b0f830c015355ba1aea47bda50f78d96f56647e4c178276aa\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"5000d00001FyVLOAA3\"], \"sfkbversionnumber\": [1], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"As <a href=\\\"https://stackoverflow.com/questions/6901108/the-total-number-of-locks-exceeds-the-lock-table-size\\\" target=\\\"_blank\\\">this post</a>\\u00a0shows, increase the innodb_buffer_pool_size variable to 64MB for MySQL server. Here are the steps as per the documentation:\\n<ol><li>Locate the file\\u00a0<code>my.cnf</code>\\u00a0from the server. For Linux servers this will be mostly at\\u00a0<code>/etc/my.cnf</code></li><li>Add the line\\u00a0<code>innodb_buffer_pool_size=64MB</code>\\u00a0to this file</li><li>Restart the MySQL server</li></ol>\\n\\n<p>To restart the MySQL server, you can use anyone of the below 2 options:</p>\\n\\n<ol><li>service mysqld restart</li><li>/etc/init.d/mysqld restart</li></ol>\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m7JQAAY;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m7JRAAY\"], \"kav_id\": [\"ka10d0000004TOaAAM\"], \"sfresolutionc\": [\"As <a href=\\\"https://stackoverflow.com/questions/6901108/the-total-number-of-locks-exceeds-the-lock-table-size\\\" target=\\\"_blank\\\">this post</a>\\u00a0shows, increase the innodb_buffer_pool_size variable to 64MB for MySQL server. Here are the steps as per the documentation:\\n<ol><li>Locate the file\\u00a0<code>my.cnf</code>\\u00a0from the server. For Linux servers this will be mostly at\\u00a0<code>/etc/my.cnf</code></li><li>Add the line\\u00a0<code>innodb_buffer_pool_size=64MB</code>\\u00a0to this file</li><li>Restart the MySQL server</li></ol>\\n\\n<p>To restart the MySQL server, you can use anyone of the below 2 options:</p>\\n\\n<ol><li>service mysqld restart</li><li>/etc/init.d/mysqld restart</li></ol>\"], \"foldingchild\": [\"c18ed3d36f5b0f830c015355ba1aea47bda50f78d96f56647e4c178276aa\"], \"sfcreateddate\": [1511531908], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1513683920], \"kav_summary__html_stripped\": [\"\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Coveo Enterprise Search\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2\"], \"concepts\": [\"MySQL server ; error message ; post shows ; running log4nets ; V2 org ; push source ; documentation ; pool ; Resolution ; lock-table-size\"], \"sfkbid\": [\"kA10d0000004MijCAE\"], \"kav_firstpublisheddate\": [1513629714], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"c21e283e0602160acefd4055caf8fbb9293a49f369d0c9b07150724b915e\"], \"sffirstpublisheddate\": [1513629714], \"sflastmodifieddate\": [1513629714], \"kav_coveo_version__c\": [\"Coveo Enterprise Search\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Pierre-Guillaume Laurin\"], \"sfarticlenumber\": [\"000002820\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o0d000000m7JQAAY;02o0d000000m7JRAAY\"], \"kav_description__c\": [\"You are unable to refresh content of a push source in a Cloud V2 org. When <a href=\\\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/logging_information_with_log4net.htm\\\" target=\\\"_blank\\\">running log4nets</a>, you get the following error message:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nMySql.Data.MySqlClient.MySqlException (0x80004005): The total number of locks exceeds the lock table size</pre>\\n<br>\\u00a0\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka10d0000004TOaAAM\"], \"kav_articlenumber__stripped\": [\"2820\"], \"sfversionnumber\": [1], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_validationstatus\": [\"Reviewed\"], \"coveo_foldingparent\": [\"c18ed3d36f5b0f830c015355ba1aea47bda50f78d96f56647e4c178276aa\"], \"collection\": [\"default\"], \"sfsourceid\": [\"5000d00001FyVLOAA3\"], \"date\": [1513683920], \"kav_lastmodifiedby.id\": [\"00560000002MKBSAA4\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000002MKBSAA4\"], \"kav_lastmodifiedby.name\": [\"Karel Mpungi\"], \"kav_articlenumber\": [\"000002820\"], \"permanentid\": [\"4ad769ada5a24cc2e1eca2648004d18f4e33084931854eae804a83de45fd\"]}",
      "sflastmodifiedbyid" : "00560000002MKBSAA4",
      "syssfownerid" : "00532000005ZlvdAAC",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Unable to refresh a push source: The total number of locks exceeds the lock table size",
      "rowid" : 5493292,
      "syssfcreatedbyid" : "00532000005ZlvdAAC",
      "sfdescriptionc" : "You are unable to refresh content of a push source in a Cloud V2 org. When <a href=\"https://onlinehelp.coveo.com/en/ces/7.0/administrator/logging_information_with_log4net.htm\" target=\"_blank\">running log4nets</a>, you get the following error message:<br> \n<pre class=\"ckeditor_codeblock\">\nMySql.Data.MySqlClient.MySqlException (0x80004005): The total number of locks exceeds the lock table size</pre>\n<br> ",
      "size" : 4482,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1511531908000,
      "sfsourceid" : "5000d00001FyVLOAA3",
      "clickableuri" : "https://na61.salesforce.com/kA10d0000004Mij",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00532000005ZlvdAAC",
      "orderingid" : 212384990660372100,
      "sfpublishstatus" : "Online",
      "syssize" : 4482,
      "sysdate" : 1513683920000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Unable to refresh a push source: The total number of locks exceeds the lock table size\" uri=\"https://na61.salesforce.com/kA10d0000004Mij\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "CAD",
      "sfkbid" : "kA10d0000004MijCAE",
      "sfcausec" : "As the error message points out, this is due to the <a href=\"https://stackoverflow.com/questions/6901108/the-total-number-of-locks-exceeds-the-lock-table-size\" target=\"_blank\">total number of locks exceeds the lock-table-size</a>",
      "sfdcexpandedproduct" : "All;All|Coveo Enterprise Search",
      "syssfcreateddate" : 1511531908000,
      "sflastmodifieddate" : 1513629714000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Karel Mpungi",
      "collection" : "default",
      "sfdcproduct" : [ "Coveo Enterprise Search" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187597000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Pierre-Guillaume Laurin",
      "sysclickableuri" : "https://na61.salesforce.com/kA10d0000004Mij",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1513629714000,
      "sfownername" : "Pierre-Guillaume Laurin",
      "sitename" : "Community",
      "sysrowid" : 5493292,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Unable to refresh a push source: The total number of locks exceeds the lock table size",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA10d0000004Mij",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MijCAE/language:en_US",
    "Excerpt" : "You are unable to refresh content of a push source in a Cloud V2 org. ... When running log4nets, you get the following error message: ... Cause ... As the error message points out, this is due to t...",
    "FirstSentences" : null
  }